<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Récup Num FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>70b2a6eb-f93e-408e-81f4-9b5475ff8607</testSuiteGuid>
   <testCaseLink>
      <guid>5c808c70-21b9-4857-8ea4-3a158c675ed4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Menu Récupérer mon numéro/Consulter le menu Récupérer mon numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>064dde95-7b0c-4cbd-a5e0-ddad3ed28d28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>516702b3-511a-4e61-9c25-0c06fa22b779</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/02-Saisie Numero à récupérer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20147e97-a8f1-4eb5-a223-75723ff56209</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bddb5f6-b36c-4684-a15d-227b1b3a063a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/03-Saisie Pièce d identité</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>174bddf6-5991-4b6c-a208-05f0944a5bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8901dfa8-b3a3-429b-9e00-b11e005029d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8c3ab35-7696-4bd5-9b80-cf1b0fefa8af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/04-Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>995ec3bb-ea13-47d1-bfe5-dfdb81190853</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>621069da-426f-4782-9532-fb68bb146509</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b48b330-6094-4ca4-b65b-f3c4e61b9ae5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b65cef24-b587-4b6c-b21e-4084cf0a205b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/05-Confirmer saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b448e55-4bfc-47f9-8e0f-ae3359006a1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ade373-fd7e-4186-a83b-2a7cc92f3183</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40564960-7db3-4ce8-a3fb-ea884ed865b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99451fc3-6b8a-4926-9068-925f2c8c9436</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19d3f91b-75cc-4cf8-aaea-12ae5f2d8340</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/06-Récuperer mon numéro - cin différent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87ce73a3-22d5-4408-b447-c6a364158205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d670c6c4-1d92-4b06-a7dd-a2b54612ab1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a74b7bc7-b003-429b-b7d2-c996a5aaf1e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c229ab0-b3e0-4781-996c-37ccfd6780c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/07-Récuperer mon numéro - 2 PIN différent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a22a81c-2493-450b-b85f-ffcedb4ac81d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bafd7c47-5aa4-42de-a71f-e739fcf26309</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce2ca28-c61a-4a4b-ab31-ac327282e8e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>641715fd-49ad-449c-99b9-771c415df1c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/08-Récuperer mon numéro - Client inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>455cd152-4dbc-417a-b360-a75af2e000fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42d31d84-6c97-4c2d-b359-de5d6d76688b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f6d8eb2-f46a-48b4-bdcc-f95af466ad93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/09-Récuperer mon numéro - Client non bloqué</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb92c2f-6204-4378-a856-e0f431c4952f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f5e98a6-98cc-42db-941d-8aa2208443ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9359bbac-48ed-4c75-a763-0523bafb0bf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/10-Récuperer mon numéro avec un numéro non certifié MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ef2d670-e672-4f2b-b90e-114cbadeded3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eef3eed2-f7ef-41c0-8cb3-28f695e8738a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/11-Récupérer mon numéro avec un numéro déjà utilisé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26e1c74-7a1b-4138-88c5-e6145985796c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db1a9372-9392-40cd-886e-b1f59d1d4ede</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/12-Récupérer mon numéro avec un numéro Postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b52027-d504-4bc1-a505-c59cf725c4f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3765966b-217c-47f4-9d3f-303e0baa736b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/13-Récupérer mon numéro avec un numéro non eligible (suspendu)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5801df93-9f50-4578-aed4-90e1c9d9c0bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0922e618-14a3-4e3a-b451-c0af166e043e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Récupérer mon numéro/Récuperer mon numéro/01-Récuperer mon numéro avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8480c747-e572-487b-952f-749069f05fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc3c9ff-b873-4feb-a3f0-a789da49db82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bef8dde-02b3-44a6-91b1-e85d410d5347</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80964c28-9de5-4f5c-a7e4-573db1d0a9fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97714e08-c2dc-4c84-b090-02a770283827</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00-Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
