<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>debug ts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0402360-cce9-4266-81e7-4aabe4ae2563</testSuiteGuid>
   <testCaseLink>
      <guid>f2a852ff-848b-4204-83a9-fc543726fb64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/MORA/02-Acheter offre MORA/05-Achat MORA pour soi - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87a7da40-aed6-431c-9c8a-8d1240eb6a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6908c7d-7c23-4fa9-ba54-d3696bf338e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0cabf05-d418-4db7-971e-3dc631c23438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/MORA/06-Limite d achat MORA/01-Nombre atteint journalier - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec322cf2-9060-422a-b6fb-8478084f71e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ee75f2d-ce42-43cb-b460-c23d0b2098e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/MORA/02-Acheter offre MORA/06-Achat MORA pour soi - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad270b9c-5d72-40c1-8299-b62c59835853</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea405ea-ff3c-46c0-aff2-0e0b6a6612d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0e4848c-0dfd-403a-9750-ba4a3dd4d1ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/MORA/06-Limite d achat MORA/02-Nombre atteint journalier - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6b7eca-d668-4754-ab26-4d25d4bac025</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
