<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>debug ts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0402360-cce9-4266-81e7-4aabe4ae2563</testSuiteGuid>
   <testCaseLink>
      <guid>f533dbd6-edb8-4507-9db2-59ba848f0afc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/02-Promotion - Achat YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe33b16-756d-401e-8dc7-887e71aff55b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2e473c1-cbbb-4a31-b68a-296710b93eff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e343bfa-5a04-4056-bf86-7553498d7bd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/02-Promotion - Achat YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe33b16-756d-401e-8dc7-887e71aff55b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2e473c1-cbbb-4a31-b68a-296710b93eff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecbcd741-094d-4325-ba11-e3b1eeee2a65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/02-Promotion - Achat YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe33b16-756d-401e-8dc7-887e71aff55b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2e473c1-cbbb-4a31-b68a-296710b93eff</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
