<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Achat MORA pour soi via Crédit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>32e93743-8a36-4260-aa23-ab921011440e</testSuiteGuid>
   <testCaseLink>
      <guid>a5dee331-fae9-4971-be3c-10c47094edc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM01 - Achat MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6928aece-5909-4247-9094-6af9437ef95c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a053870e-353f-4167-989b-6f9f5dd4b15f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM02 - Achat MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ffdf79-8e02-47d6-ba66-d19971a60ade</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f4b8beb-13a7-45db-b946-2be66123e817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM03 - Achat MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa005375-e12e-4c31-9378-f29aee638ffe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b2e329d-ba20-493a-8510-f24e9e654387</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM04 - Achat MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0806e132-0249-4f71-a770-96abc03c09d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>543e33bd-882d-4183-aa8c-4e3ffde612ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM05 - Achat MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c8661b9-4eb1-47d8-a5c4-00550765fc07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a33d2dc2-b0bc-4187-8b0d-4d75e157c99e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM06 - Achat MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0646cab7-c1a8-4e21-8c94-febf89b5c891</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf1ab31e-f1ea-4b04-8f60-cf85e47b96fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM07 - Achat MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ad5a8f6-1ef9-4dde-8715-44409b8813cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80df2043-5b94-461f-a764-b9e85cce8d16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM08 - Limite d achat MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aecee26-29bd-4066-a6eb-0e9002526148</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e49f6f5a-7ecf-4cb4-bfad-08ef1d5e03a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM09 - Limite d achat MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97add279-4833-4e01-8f39-d0addbd074ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d0c903c-37bc-432a-906b-2085885f0f8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/SHORTCODE 611 et 655/Achat offre (611)/SCAOM10 - Achat MORA avec un solde insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cda6c6c-2403-4f58-9d81-fe7f03739be7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
