<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Achat TELMA NET pour soi via Crédit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2a445271-7121-4016-9a9a-e9d7daf383b8</testSuiteGuid>
   <testCaseLink>
      <guid>fbd6803b-4244-4e08-9d08-e3499d0c0659</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT01 - Achat NET JOURNALIER One NIGHT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adc8cff2-67bd-4ecc-b3da-9d01e7008bce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb7873ed-e2b0-49b5-b597-3ebc6358a572</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT03 - Achat NET ONE WEEK 350Mo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>804bfc99-dc3d-48ef-ae77-301fdcaaa2ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>831a2bb1-0e42-40ea-9b64-e936f0c5fe76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT04 - Achat NET ONE WEEK 800Mo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a813db95-02e4-479b-bd7a-4d12eaa00109</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>674ef469-7341-4034-8b03-2375e4c180a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT05 - Achat NET ONE WEEK 2Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc042009-e6c5-4857-9084-cda8fadb7d60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39a1b61a-dd58-4718-91b2-0a8883cc5a61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT06 - Achat NET ONE MONTH 2Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da5e22cd-5987-4b89-97d7-dc137413bf3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0efb7dd6-fa0a-4886-820d-3d057a20c81a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT07 - Achat NET ONE MONTH 4Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2334e3e-039c-4c75-8c98-58798c73cdf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>730f7f38-08db-4a36-b9e2-3dece4a5d3b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT08 - Achat NET ONE MONTH 12Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1b9d3fa-da92-48ab-853e-f14ac0dac5d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d2cf6e0-fd91-42b3-91ab-c36d162970ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT09 - Achat NET ONE MONTH 25Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ed6551-370b-4575-a3ee-19cf6d0ae888</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0aafe7b-b05c-4cf0-84f7-0d21a9d8c00b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT10 - Achat NET ONE MONTH 100Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe5237fa-006f-401f-99ca-32fac6fac5c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68f0443e-862b-468f-a1ba-a3d7a5d4f8d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT11 - Achat NET ONE MONTH 100Go - Solde insuffisant</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2c2e4b-576e-441d-8436-92253be344ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>232c273c-9524-4a02-aff5-613a2c1fe1b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT01 - Consultation NET ONE NIGHT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5434ab3-41ec-4823-b2b5-b997732f8358</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05bc0670-5d89-48ca-b5e9-799c9b369344</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT02 - Consultation NET YELOW ONE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5216cba0-9f38-45ca-af14-bab74beadaea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb705eb9-3ec8-49a6-a3af-faa0a511419a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT03 - Consultation NET ONE WEEK 350 Mo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b1764fa-1ca3-47b4-850d-bdb9ef690551</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ecfdce2-f148-4d76-b033-1bfbadd7870d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT04 - Consultation NET ONE WEEK 800 Mo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a541a6cf-0082-4b2b-a891-00521bedc1cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ec06ddb-c9dd-446a-8675-3623660d742d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT05 - Consultation NET ONE WEEK 2Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73e6660d-67e8-49f8-9536-5a272d173d63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c2687e2-b8d3-4f73-826e-1a4660d3f60f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT06 - Consultation NET ONE MONTH 2Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed56a029-2cb8-490b-bca0-fc3f9685a4f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c21d2edf-3f4b-4e19-8048-8d825595d6d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT07 - Consultation NET ONE MONTH 4Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bc45261-c6fe-48b7-a6f9-58526a1bef2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47446124-da66-40fb-b041-8574417098ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT08 - Consultation NET ONE MONTH 12Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e3b8102-5ca3-4337-a7ce-16ab3ee44c2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cd68a18-42be-4e53-9f71-d561bdf74d7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT09 - Consultation NET ONE MONTH 25Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe6f0cff-ec94-445a-9609-ee0392fbd524</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f87fa75b-9c78-40c6-a6a5-9642d45770ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT10 - Consultation NET ONE MONTH 50Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>314ed455-7b00-4f39-9b05-d260313b727e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18d092a9-2c17-4e61-95cc-17102ecaa22a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat offre (611)/SCAOT12 - Achat NET ONE MONTH 50Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6bdcf64-f86b-4d83-ba5f-a7211340cacc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a7c53f9-a7ac-4abd-be0a-6e0881757bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Consultation Bonus (655)/SCCBT11 - Consultation NET ONE MONTH 100Go</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>994a904e-067d-4897-9d75-4a48263488c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
