<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi offre MORA via Credit (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5d6a769a-26a1-4b84-8607-b823f2b8cac1</testSuiteGuid>
   <testCaseLink>
      <guid>c4de9f6a-4dc2-4da6-a1d5-49b284650ae1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM09 - Envoi MORA NIGHT - Envoyeur postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d76671e3-b7ba-4e97-a91c-f86dec971133</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ae6fe6-1f61-4412-b2cd-99d96492f7e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2bf4a6f-1b64-4d9f-91be-2ad6160f9333</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM01 - Confirmation achat MORA 500 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28011ca0-de01-44d7-bc81-344f7548c08f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e61dff2-821a-4c0f-8f79-adeef3507f29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c835809c-d790-45bb-8fff-50ba1108f0dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e79242da-3ebe-4f0c-be8e-f845f6ed2897</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM02 - Confirmation achat MORA ONE pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec5c65d5-67f3-4a24-b9dc-3dece4890699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63eb4a33-4ad3-4731-8970-15e39f8d93f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6581c70b-39dd-46ba-9bec-67da7e2d9f99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd5a4364-22c8-49f1-8614-9b1f68672bb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM03 - Confirmation achat MORA 2000 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4ee903-3a63-49c9-b821-ba21aaca41ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2daf098-dcc8-4665-8e88-f2d9cf3ec247</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9170fe6-22bd-418a-b410-a57690164d30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a630643-3629-44b2-b221-7cd2c0c91cbf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM04 - Confirmation achat MORA 5000 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>788980a3-207a-4243-951a-be9b48c3380d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49ab8960-2089-4c9d-ab4a-5ad2e0566dbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be087c97-c05a-4a95-b540-687808eea779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47e638c0-b64d-4c89-9d32-51ca32e33306</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM05 - Confirmation achat MORA NIGHT pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06980d0e-9f53-442d-93ae-63b9a23db15a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7902e83c-2be8-4fd2-8f5e-758efce2e35c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b391ee-ef43-4482-914c-355280c0082a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bce7f94-5513-4de9-abda-dc8150ecaef7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM06 - Confirmation achat MORA TEAM pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39634f67-33fc-4d82-a110-1c08b5ecd327</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3aaa0d4-5387-4b69-8806-b7816d123bb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8294b8fd-c874-405f-ac6e-80afc6f6ff5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5733adc9-233a-47d4-be47-fdb1fc8fd005</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM07 - Confirmation achat MORA INTERNATIONAL pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1039f7de-a050-475b-bb05-5c3df9d45ed9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d1d0a39-d6eb-4514-8af7-f62c8a2669d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>379f1e30-dea8-4e68-82f1-0e3b8c291a3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e50536f-64ba-4b6c-bd06-3f5a138a888d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/01- Achat MORA pour un autre/SCEOM08 - Envoi MORA NIGHT a un recepteur non eligible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1da8189f-1909-4379-81a7-2f0e0e237e9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71da5b3d-00e1-48af-a981-8742dfb5df38</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
