<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi offre YELOW via Credit (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>23e5ee31-3a60-48f9-86f0-4ae201075b57</testSuiteGuid>
   <testCaseLink>
      <guid>e28f434d-aeba-4039-9b3c-b873317069a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY10 - Envoi YELOW SMS - Envoyeur postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e180cef-fa2b-416f-8642-d8df3e32bd0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1ebad7-8579-4f86-80b1-d40a387e6b9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a758054d-46c5-4b1b-bf73-f44e5a0a3a70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY01 - Confirmation achat YELOW 100 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd60ac0f-c1e6-4b2c-a314-b94a91600652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6976f393-4d19-4191-9812-3e68cb4625e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fcea75-25d4-4cfd-b51f-5b116b10e09d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56d9d2ec-f9c6-42d9-aed8-cdda870e39e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY02 - Confirmation achat YELOW SMS pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4de7cfe-0911-4441-8ba4-1568ee80e954</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>744eef72-d01d-4f62-896d-de153b52112e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6831a436-708d-4ed1-80df-e7259a955a56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>154eea6e-b43c-4ab8-99e0-28eb852be0ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY03 - Confirmation achat YELOW FB pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a56aca2-6d04-4293-be03-98efa16c8895</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6944365-1119-4148-b865-2499d5c80351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03881704-fbd5-4ac8-82b7-290691f4dc8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a96cf3fb-1a58-4726-83c4-e18272374409</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY04 - Confirmation achat YELOW 1000 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aab628b-0a81-4d28-aa8f-5c349e8e6fc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26d2c2ef-61f3-426a-a6e3-dd07d43c91a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a505fa6-fecf-4303-ac42-8ac880a94f36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1d45593-406a-44d1-97d5-40102b46e37c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY05 - Confirmation achat YELOW 200 pour un autre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f654e556-e02f-4199-8ed2-fafbefd7caee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>054f1f4e-5630-4cff-8819-0ba28b59b8b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f28f7689-9546-4b0c-a98b-5af5e7e9aa05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19ad846f-f44b-498b-8d4c-439e4b0860d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY06 - Confirmation achat YELOW Faceboobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69dee952-0348-4c04-86f5-78e4b14190dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3efc568f-0e7e-4aa9-87e1-3637a4f1588d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1386d104-d50c-4c27-9f2e-56f380c27fcd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c26f50b5-a2da-4f2c-9253-38e12a76a2df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY08 - Achat YELOW Faceboobaka - Saisie numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8259aeba-3331-4980-957e-644f2c099993</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52c1d490-d825-4741-bb28-dcf0ef15f19e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/03- Achat YELOW pour un autre/SCEOY09 - Envoi YELOW SMS a un recepteur non eligible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b814b932-0339-4274-8bae-53ef54d3ffa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af7a299f-cf7a-411a-805e-b7e33752d8f6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
