<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi offre TELMA NET via Credit (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7b1efd18-7492-4a03-9d93-f8ef951d7220</testSuiteGuid>
   <testCaseLink>
      <guid>515881a6-988f-487f-90da-b080d67f983c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT10 - Achat TELMA NET - Saisie numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>234d739e-0b9b-4a07-a853-57c5b792e157</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f9c0c84-f50a-4f77-9b7e-d6c7382f66ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT01 - Confirmation achat NET One Night</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d2782df-e0b7-49d2-a2f9-076a191b7561</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3be200db-c3bd-4e2e-b39a-6ad76a7795e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbbd23f5-4a47-45f5-8669-ea51e53a6d37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e950837-015b-4d7c-9e72-270c6857c394</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT03 - Confirmation achat NET One Week 350Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de1d8bc8-8a10-4cf3-b948-a555540d0538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fa3ce2d-6ad8-4a46-aefe-d70d92028476</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e3137a-9f26-4c7d-9ec2-4b00af1a238c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01ca41c8-b471-4db6-9998-75b1f04a4a7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT04 - Confirmation achat NET One Week 800Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f80f515e-343f-40e6-95bd-b8f0ef84a492</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a406b67e-14f2-4cd2-ad36-472b38590c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e498454-47cb-46ae-94f9-8be3b7b8c8ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68a7fe11-4d42-4eb8-abe1-5698ce400f87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT05 - Confirmation achat NET One Week 2Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9203c44b-dac9-4178-a74e-52b634559f6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83905e77-9d79-47d6-af29-904c1c667159</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3db95614-1219-4f7b-818d-1e47caec0a34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0be5f47-dccf-4257-9bda-0a28f7d7ba9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT06 - Confirmation achat NET One Month 4Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4271543f-470f-4a47-8967-7cd896eed974</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59dd7057-6681-4662-b717-66eca53f2ed8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c75d28cf-2a67-4c45-aa5b-96a2eed728c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97512536-9d72-4251-8e81-f41c4103d37a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT07 - Confirmation achat NET One Month 12Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3865a62-1d84-442b-80c4-f11c5e236994</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc3da127-e2d5-4cb9-b288-185816851bc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d290666-3953-46b6-aa7b-0b60c2ce453e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9688ff4d-a58d-4b84-843a-04db11aa9acb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT08 - Confirmation achat NET One Month 25Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce399d4-2762-4d6c-b29f-d93c89888366</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec411a43-ff5d-4b1b-9257-17ce2b2534ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391508dd-e1f1-4d23-955a-89ea98d649f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79c401d7-b1d3-4856-8744-886c542d91ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/04- Achat TELMA NET pour un autre/SCEOT09 - Confirmation achat NET One Month 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>439b50d2-1956-443b-8d90-82b3d6388d05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>744a7498-5e82-4926-8938-a8305d067699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db9a6d31-60c5-403a-8c5c-8060a8216ab4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
