<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Yelow FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>37d7b3a6-ddc1-48d3-b724-49951d97b0fc</testSuiteGuid>
   <testCaseLink>
      <guid>ec5c5a1d-1b1c-4039-a0fe-585a06ced7a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97e7f08c-32c1-448f-b32e-2e8ccc90dd9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/01-Menu Yelow (SMS - INTERNET)/Consulter le menu YELOW (SMS - INTERNET)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d57d62-bc94-440a-972f-88da417bd059</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6343c705-e777-4742-9151-f3216914b0eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Non elligible à l achat offre Yelow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad59dd24-03ab-43ce-bc2c-e9b71ff2e107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80531d74-fb56-488d-aa85-c152e7678e1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80cbdd58-bfc9-45b1-8eb4-816d6a84c37f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow avec crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d79176ea-7947-4187-92a2-69b2b08bf9f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4c24283-c1c5-4c6e-ba2e-e238d7154808</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4ca4bc9-e9f2-4e1a-b165-7911d6282b10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW100 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80114e65-62df-41b8-b32b-619041f39c74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c63b0d-8c42-4e95-a08a-9e2304fbe06c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85798648-6d0e-4185-a774-b0ae26ff8e17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW SMS pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34e047d8-c070-4570-9242-1ebb36aba141</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8f3c704-8a16-4db9-a082-34d2b37eca7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9f4abd5-df55-4d98-916f-0271613d0ee0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow Facebobaka pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a490d745-3218-4f5f-b6b0-a636e3b3dda2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b49c9d01-17d0-4d3b-92ca-43727f6df345</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>480d4bc1-f729-4fb4-93e5-881ca5174057</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow Facebobaka plus pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57510e91-f119-4433-a58c-a01e4e8b8128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ade298-8100-4f1c-9975-9e3b523ad9f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>305dbcf6-0879-4f4d-9fe3-f2d1f8c7f996</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW 1000 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aedc1a3-4f5e-4b40-9aca-54914786331e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff8f3acd-9710-423f-b390-44aa16dc4b5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0d72e2f-91d1-4e05-9f27-cc7547ab6c23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW 200 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fedaf8f-0dcf-48eb-9537-32fe5498b66e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93c289eb-2df7-4506-95b3-8158b9319ad2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b47ba43a-2a9a-476d-a6af-bc95f892aa2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f013d39f-0381-4501-9646-42cc08ac6621</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dda5d73f-bfb7-4f7c-af6c-42885a352119</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6eadc95-53da-413c-b538-23a0dda02ec9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef1db1be-fc5f-4ba3-bf5c-9861ea5d2cb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow facebobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75cf214f-f353-4107-be25-a10d57cd63ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43170d55-0f8c-4f25-ab60-92c9dae1bcc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f8b0306-e762-4afc-888b-500b8918917a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>891daae4-83df-493e-bedd-05dc79afd0f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/04-Consulter offre Yelow (SMS- INTERNET) (359)/Consulter offre Yelow 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c19a8b1-ad3b-43f6-ba6c-1042f63c18c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22b28ae0-1657-4db0-a39d-683b505896bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/04-Consulter offre Yelow (SMS- INTERNET) (359)/Consulter offre Yelow 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec16ca12-b3c3-4b85-a57e-79539bbed433</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37a6c58e-f1ba-4e97-964d-bf5c59599410</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/04-Consulter offre Yelow (SMS- INTERNET) (359)/Consulter offre Yelow SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7896fb2a-03af-43d5-a11d-647e4d9b9bf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05ed25c3-ec16-4ba3-ad2a-cb16b71611c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/04-Consulter offre Yelow (SMS- INTERNET) (359)/Consulter offre Yelow Facebobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>748cc56d-d5a2-4699-87f6-e4f6ec1afbe1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1f4a8ff-1d45-4512-9a3e-c67502eed405</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/04-Consulter offre Yelow (SMS- INTERNET) (359)/Consulter offre Yelow 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afbb32be-db72-4440-a111-cce14d55ff69</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
