<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Configurer mobile (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>37e57202-5c40-426e-a758-869bc1a6e62c</testSuiteGuid>
   <testCaseLink>
      <guid>3573141e-fe37-4f4b-afe1-54c35c0399e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/01-Accès USSD/Menu Configurer mon mobile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd580d74-e065-44fe-9ae1-705f4f5531e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86c70e53-6eb8-4baf-853a-899b3c30ef46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/02-Configurer service WAP/Configurer service WAP - Succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b54f8e01-d48e-4c23-8cdf-7b3a0c281377</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7bd3755-3ab7-4023-9c9a-9c2e2d5ec1c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/03-Configurer service WEB/Configurer service WEB - Succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6a4c317-8bff-405f-a727-e78d6383c07f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>929ebbf8-4d88-4336-aa7c-a5ed4d423daa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/04-Configurer tous les services/Configurer tous les services - Succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8486e741-8c31-4e7b-bfdd-536c92913184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffdc3966-8e3f-4b69-9138-61266ba84d67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/05-Activer INTERNET sur compte principal/Annuler activation Internet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8fd8abf-3845-4b18-bd8b-15b7dfb1f890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f3f1d69-c6f6-4cbb-b5c4-8e86b57d3f6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/05-Activer INTERNET sur compte principal/Activer Internet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8478952-e974-4667-879f-2afa4340dcb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>086761d9-1b2c-4ff2-9783-e7da89741ebe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/05-Activer INTERNET sur compte principal/Activer internet déjà activé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4784c1-4924-4d0c-af44-a038d30f1ea7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5df2e3e9-3f13-42e3-9f3c-f94d99b1c148</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/06-Desactiver INTERNET sur compte principal/Annuler désactivation internet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d788b770-ff61-45bf-a984-86fcec3fbb8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6eb4d27d-70db-47ee-b34e-debe272ce16e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/06-Desactiver INTERNET sur compte principal/Désactiver INTERNET</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66ce78c1-b8d4-4711-8668-e6fb845695f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0068be83-1b0f-428b-84b3-0f333b142bdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/06-Desactiver INTERNET sur compte principal/DésActiver Internet déjà désactivé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3bc77c4-392c-48a0-990a-91319826248b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6c7a2e5-2840-4d5b-8e41-fe87704ad7c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/06-Desactiver INTERNET sur compte principal/RéActiver internet désactivé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8557cb-8de8-4dd0-b0c2-0225702568b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>802963f5-828a-4222-9dbe-80109bfe560c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/06-Desactiver INTERNET sur compte principal/DésActiver Internet - limite mensuelle atteint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce13118-77cd-42d0-93c4-578ab1245d47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0dc86db8-e644-4d05-92de-a4954978cf98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP Mvola/Generer OTP Mvola - Keys incomplet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1528b4a-b4a8-4868-af8e-1373c4bab570</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be16948c-7361-4c6d-8079-8432601d442b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64372eab-e7c1-4e40-938e-dd3858f79858</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP Mvola/Generer OTP Mvola - Succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c61b839b-3fcc-4d37-9eaa-1cf6a36f084e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>987457d6-1db1-4fe8-81bb-2172c48fc20e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d936e64d-6633-44f8-a458-65b98b3101bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP Mvola/Generer OTP Mvola- Application Mvola déjà installée</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54cb92f5-c967-4e60-8483-1122427cc7c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c9390ee-9d33-480f-9d52-2c0222049f90</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fecbce9-151d-4cb2-aece-4d7f9afbb55f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP Mvola/Generer OTP Mvola - Quota journalier Atteint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ea20f6d-62cd-4c8f-a8a7-58b0992def97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba7ba75c-e567-4849-a48b-af2147720b37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3303ca1e-a43a-4c61-8f9f-36b9e69c5758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP TelmaEtMoi/Generer OTP T M - Keys incomplet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0094267-4cbf-4420-ac17-355624d70951</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e10cf9df-457a-402a-b0e5-9e70d95e94ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aff6f2bb-9281-43b4-abc7-fedefe568f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP TelmaEtMoi/Generer OTP T M - Succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7dc241c-769c-41bf-95c2-3936a4cb210b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ead2692-07ec-41e7-a018-472826832c65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4199113-034a-4992-a434-860531bf7ed6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP TelmaEtMoi/Generer OTP T M Application T M déjà installée</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66070128-76fd-4ec9-8b94-bdc3ef3033ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12b8852b-dbc8-4fab-8b1d-dcd652af6604</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9214d6ef-67e7-4ee3-b7c2-6ffeb92b7e6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP TelmaEtMoi/Generer OTP T M - Quota journalier Atteint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91240428-2702-4fba-9a01-256765d442b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3350ee90-e057-4fe7-8fca-fb567355c0e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84cbeb81-cd32-4e5c-bee1-22bd1fd0abca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP Mvola/PIN Bloqué</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47af3e44-03de-40e1-81e5-1266a07be921</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a7a9510-f38f-423f-9674-bb87665185b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Configurer mon mobile (Semi auto)/07-Generer code OTP/Generer OTP TelmaEtMoi/PIN Bloqué</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8009e5eb-a834-4d29-945b-1a3b0a028609</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
