<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SOS Crédit FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>68fd60c2-c7bb-4b08-8826-c545aeeb114b</testSuiteGuid>
   <testCaseLink>
      <guid>232b4cdc-8289-417b-9a83-401b803c3365</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/01-Menu SOS Credit/Consulter le menu SOS Crédit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10988d09-405c-4e83-a200-c4fd49a6d6da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2a9eb0d-acea-4696-81b2-0e9b6324c764</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/02-Demander SOS Crédit à TELMA/SOS crédit avec un client moins de 3 mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a9f4419-47ca-4e5d-87ce-12cdf326fdef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>803078a5-39f4-4869-9c6a-2811e0fab8a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/02-Demander SOS Crédit à TELMA/SOS crédit avec choix montant invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bf3cff0-6e0f-496e-a54e-378c07422309</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>046876fe-2995-424c-8387-e1ed7f1a088e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/02-Demander SOS Crédit à TELMA/SOS crédit avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b4bba0c-1f8c-4683-be13-ab1b8794268b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da91a246-0aaf-4a0d-823f-3ab7aca1c48a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3516b696-b3d7-46ba-a365-e17240198022</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84c62da6-890f-4645-9e22-5faa3bb67204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/02-Demander SOS Crédit à TELMA/SOS crédit avec un client ayant une dette</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd76488f-239e-4e0f-be12-e8402898c9fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8060a3a1-72ba-4b82-9b83-fe9d922f8c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/02-Demander SOS Crédit à TELMA/SOS crédit après Remboursement du crédit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3aa698c-5ff4-42a7-acde-f0705c1e4c2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7c4943e-12c2-4235-be1e-d30e0a8fe9fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28f660ad-0092-4499-a5ef-db0cda0b5003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fee5e616-da38-4442-8f3a-7aa20a6e7841</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/03-Demander SOS Crédit à un ami/SOS crédit au numéro de soi-même</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c049d71e-9559-42d4-a383-c5ee7f231b7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a491fb8-5d99-48d6-b9db-6c19c0bb67fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/03-Demander SOS Crédit à un ami/SOS crédit avec un montant non inférieur et supérieur à la limite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdded510-30ec-43e9-8611-68d33e7a1c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f08429a-67a2-4d76-9ba3-6ff8844e2241</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d5938a1-b955-437d-b752-f581893605a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/03-Demander SOS Crédit à un ami/SOS crédit à un numéro non TELMA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>572ec8aa-48b4-4adb-8d86-f7d18f0b80d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bb08cf4-53fb-443a-bafd-b37bb0c9c30e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/03-Demander SOS Crédit à un ami/SOS crédit à un ami avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08e08c71-eb22-4ca7-87bf-56ff6e537959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>161c3275-278e-4e07-9fd4-64c462d738aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab6ed83b-83c9-43df-b807-efff0fd7f01e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20ce95c6-2096-4918-b946-563ae5c6bc3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/03-Demander SOS Crédit à un ami/Limite journalière SOS crédit à un ami</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>401fa0ab-c51f-48d7-bc04-bcefeb8724ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc158a25-e4c7-4a43-aaa2-23f501c09c72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc4ffb36-4582-485b-a901-8e606683d6a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/06-Repertoire SOS/Ajouter un numéro (PIN mauvais format et PIN invalide)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b68d7ede-6dc2-4cde-8c1d-a53ec6801dde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>104a15a7-de42-40ec-be12-e42cedca2557</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6679dd2f-aad5-4fb5-ab4b-5eb936c87226</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/06-Repertoire SOS/Ajouter un numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>393b3a36-607f-4388-9c65-48188644b52a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33d6f41b-dbaa-459e-8110-9a0f45149a8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ff5b8b9-015d-419e-b03c-8065bc870a2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40b79693-b670-40e6-a325-f13a28a55852</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/06-Repertoire SOS/Consulter le repertoire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86fffe70-a358-4890-aa40-f7fc3f7b61c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>720fda38-7629-4c56-8455-39d115a5a1a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f9e0e86-91f7-4057-9e4e-525c2666f9a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/06-Repertoire SOS/Ajouter un numéro qui existe déjà</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9589ed6b-7ad6-4d8d-9593-cacfc616ffb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9612325-5983-4ea0-8d91-2c68671b4997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00c30bc3-1789-4853-97ca-f0d354b2943e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efc31d2a-a918-4603-b0cf-c1aa493325d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Demander le remboursement à un ami</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23d0ef53-7f07-4d1a-a230-26a829eeb262</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9127665-7a94-4d85-bd24-4b3493fdf1cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f28d1d51-b68c-4e87-828c-2760af8aecbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Demander le remboursement à un numéro non certifié MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b603c768-6741-446a-a6ac-0982c1704e00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f608672-08d4-42c6-b36e-8a9823c75724</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5decef-46d3-439f-810e-6c26812ac01d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Rembourser la moitié du SOS crédit d un ami</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8be97407-1943-4044-a5af-77e950a54af9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc243c3-349f-4d43-a955-10bb220e834d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d34c2cb0-abd2-4285-b01d-0708e4897d60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b223974a-d441-4f24-91aa-9b8bb7cab05e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Rembourser la totalité du SOS Crédit d un ami avec MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1aad45c-23cc-439b-a6e3-7f83271b3268</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f67337d-f999-4e6c-a5c0-57a890f2e01a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5bf82bd-7094-4ac3-ac7d-290272cdc408</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d461e890-31d4-463b-a25a-44d895bc5afc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16c7208a-7924-4acf-ba8c-91943849f690</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Rembourser un ami qui n a pas de dette</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fe7c065-afc1-4921-a261-65f5eb4e9aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0a7b9ce-2c0f-48d1-bd8a-a596eee1e527</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcc218be-f6b1-4187-a76d-83c809e21d80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/05-Rembourser SOS/Rembourser une dette inférieur à un crédit de 100 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2133c71d-52ea-424e-a4ca-876f9470bc2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1464d51-7c2b-46d9-b9c7-266f9c2c1dc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c9783b1-1ce0-496a-9d2a-950f38161d63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/06-Repertoire SOS/Supprimer un numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bcc2082-af05-47dd-baf6-d55eea93d1fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c173c87c-a497-412d-9e8e-b3891553d190</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87ef6e95-3284-4fbe-954f-93026ebdc0cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/07-Aide/Aide SOS crédit à TELMA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8109a929-a807-48c9-97ae-21bfddde02c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77781e00-a799-4549-975c-f0dcfa4ba999</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/07-Aide/Aide SOS offre à TELMA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64816a15-2941-4695-aeab-5431c2237354</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eaa01868-628f-4050-b9fd-295b7a4e5a79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/07-Aide/Aide SOS crédit à un ami</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b38c6c0-e69d-459a-9d75-79a9f2b0b5aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cd5c039-233b-4c3a-b2c4-bbfe96eee37b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/SOS offre avec un client ayant une dette</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac78d768-35b7-44b1-9b6b-989256f7811b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2c27adc-d498-4adf-92e5-410301c04316</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/SOS offre avec un client moins de 3 mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05684e56-c427-4530-9044-f7aad6061bd1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
