<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SOS Offre</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dbdf09cd-1c85-4e81-8f11-98a9bf5f139e</testSuiteGuid>
   <testCaseLink>
      <guid>94c94a3c-9e0c-44b0-bbbc-d6af9f7d82af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/01-Consulter menu SOS Offre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ea6c1a4-e8ba-4ac3-b7e1-e1b62f3a5c9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d0e0238-8f20-429c-be6c-0b4260fe203a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/02-Consulter menu SOS Offre - MORA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1e5963-d8f2-4a0e-b803-a5484f93f630</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a5bd094-d042-409e-a9e8-65ac63ab47bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/03-Consulter menu SOS Offre - FIRST</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd432222-e5af-4789-9449-3ddc209ae33b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c71b5e5f-fa20-4ec4-8460-7a8c918af69c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/04-Consulter menu SOS Offre - YELOW</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d326613-c992-4a45-acde-f240980df6da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>664695db-624b-49af-bdd4-c2111f885359</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/05-Consulter menu SOS Offre - TELMA NET</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4917bcc9-ec2d-49a1-bea4-b8fae63752f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf112712-07a4-4ca4-8b04-1acab9882697</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/06-Consulter menu SOS Offre - TELMA NET JOURNALIER</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06b6039a-21f7-4548-8317-d4fd19f59751</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e363709-0fda-47b1-9ee5-9103dc23b082</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/07-Consulter menu SOS Offre - TELMA NET HEBDOMADAIRE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bae21781-0699-4a37-8038-9a43609b541d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>612ee7d1-973e-4c35-9662-38dd7850b07f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Consulter menu SOS offre/08-Consulter menu SOS Offre - TELMA NET MENSUEL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fcf6623-5cfb-4816-ae4f-926379df19fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1675fb2-6dea-488d-9b40-a67d266439b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/01-Prompt de confirmation - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84d04873-54eb-4060-abb9-189dc661f692</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f52bd1b-90a6-4197-ae2f-490be807ab17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/02-Prompt de confirmation - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>925de106-5fa0-46a0-a10c-dd0be6759954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ba61270-0496-42cb-aade-1eca69b88386</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/03-Prompt de confirmation - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fdb76fa-f377-4852-84c3-3d8241c46dc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b83eca7-ba22-4f51-a713-073e1d1f09eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/04-Prompt de confirmation - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee195060-cae6-4bc0-81ef-03caa7282319</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>429ebffa-0736-44e8-aca1-2007a9434a96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/05-Prompt de confirmation - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eda0dfaf-7cd0-4f66-a094-a30073801664</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8680567-56af-40c6-957d-36b70d99a4af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/06-Prompt de confirmation - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a49e829b-bc99-4028-a945-0aa6d544df14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af4c2ca6-0205-404e-9713-9d7703ec41de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmaiton SOS MORA/07-Prompt de confirmation - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddc2a7ed-4398-4918-9896-656d93d6c0b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9461624d-b2c0-40c6-8db3-a5405255355d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS FIRST/01-Prompt de confirmation - FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17a4223c-8fae-4c90-be73-369ace5c96ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f780f75-10e0-40f0-93b0-3dd6a0b49651</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS TELMA NET/01 - Prompt de confirmation - NET ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b467b2-8e81-44f2-a472-a27b14c60fc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ca7ffed-664c-45ae-90e5-719941140d1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS TELMA NET/02 - Prompt de confirmation - NET ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b19b30b5-c05c-4a96-aee2-a74f578817d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae04fc91-7eb8-40b5-9621-e018228e1e5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS TELMA NET/03 - Prompt de confirmation - NET ONE WEEK 250</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f3b426b-283f-4b80-ac71-9990fbfb5dfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6286960-4cda-48ec-9d2c-e5fadcaae5ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS TELMA NET/04 - Prompt de confirmation - NET ONE WEEK 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>093c953a-755e-4f5c-86b3-127e61d8a041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7bc228d-5660-4eef-8fcf-d6b92d1dd230</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS TELMA NET/05 - Prompt de confirmation - NET ONE WEEK 1,5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d645308-879b-48ec-8d59-67af0312769b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>929bc2d7-944a-46dc-a22c-06a39f2154e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/01-Prompt de confirmation - YELOW 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae859c49-1729-4114-806b-d53770bf5ea3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f16fd4fe-83cf-402d-b32b-fd21414e66d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/02-Prompt de confirmation - YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d52bc32c-3f96-4b39-935c-eca3b3d67bd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67e49e13-6b01-4fd3-97c2-3057f76c965e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/03-Prompt de confirmation - YELOW FACEBOBAKA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3612efb-fb64-4087-b855-86e1492f1863</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09170b59-2804-4307-9152-cd043ee365bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/04-Prompt de confirmation - YELOW 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e75ca090-1fc1-4ccb-8472-b2b3afde495a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9adc1f09-bcb3-463e-afee-b88c73765d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/05-Prompt de confirmation - YELOW 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f98880f-4498-40f9-a23b-604917cab272</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52ed487b-4cd4-45c9-b47e-754c99b124b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/Prompt de confirmation SOS offre/Prompt de confirmation SOS YELOW/06-Prompt de confirmation - YELOW FACEBOOBAKA plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8befafb6-5b50-4f0e-8093-ca40c68fcbdb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82020fbb-d7ff-4d19-9814-588514ba25d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/SOS offre avec un client moins de 3 mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05684e56-c427-4530-9044-f7aad6061bd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fb08023-027b-4ff3-8d38-ab0b743159dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/SOS offre avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1fe2af-65bc-420f-8c24-10ed4996ed22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fc4c0d3-8041-43a5-b669-c61786567a30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOS Credit/04-Demander SOS Offre à TELMA/SOS offre avec un client ayant une dette</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac78d768-35b7-44b1-9b6b-989256f7811b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
