<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Changement de code (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0c3d32e2-16bb-401f-bfec-a69e165fe68b</testSuiteGuid>
   <testCaseLink>
      <guid>121dc8fd-ef50-45db-8d24-aa1988b6289a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/04 - Changer code secret/01-Saisir code secret - User 2TMV</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e137284-d879-4adc-a8dd-1d236a90a929</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c78f4903-16cb-48de-bde3-7e8b6336b0cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/04 - Changer code secret/02- Saisie nouveau code secret - User 2TMV</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d5d1d2f-e51d-43d2-a9c1-68a3ce581bf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ae694cf-8aa7-4dc1-81d6-ea6557ef354d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295c8ed6-98f9-47f0-85b5-6ceb2788cea4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5f06ddc-5d4f-4e2f-bbfc-9d7b7d6948c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/04 - Changer code secret/03- Saisie confirmation code secret - User 2TMV</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d6b9016-cb48-4805-93f3-caa2c2ff9cfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9afa92b7-994b-419e-b14e-092fdc525ee7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>276d6f27-7609-4e03-921c-5e4836167976</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e45307d-df14-4944-b83c-85c07f5b9597</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/04 - Changer code secret/05-Changer code secret - User 2TMV</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa783fe9-d6b9-4658-b875-3f5fd9ebdf01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c5d05b1-9667-4d37-be64-2f613068af22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f73f6470-ba26-42b1-8d19-24507d55bfa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d515b5a-8dff-40ad-8711-ed690823dde1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/04 - Changer code secret/06-Changer de code secret à nouveau</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c8378dc-046d-441f-ae32-ca4df6d43443</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31dbe292-2c39-4e15-a398-4386db9745b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ea1711-db5d-4754-812d-b8c573418ca5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
