<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Consultation (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>19df7483-5936-466f-b8ce-32d9d7e1740c</testSuiteGuid>
   <testCaseLink>
      <guid>07b41969-8124-4f12-bb8c-edb98c5981e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/2TMV/00 - Called test case/Consulter le menu 2tmv</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f74f3481-e239-45f0-a53f-4e8ea453a197</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73719549-ebb4-4401-b054-e15e16c2cfdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/01-Saisie PIN/Saisie PIN invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b5057a6-fca9-4b64-9c3e-b4bef7ff6c46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>199d7acf-eb5a-432f-bfa0-dde6a6c7b196</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/01-Saisie PIN/Saisie PIN mauvais format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54d66a32-9ffe-4bbd-8196-0200af5b1d4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8be65a15-0705-4fb7-8295-ee5c2c0342f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/02-Consultation solde/01-Consulter solde - Grossiste</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a9cde3-338b-4b30-90e5-ea2485bfb0ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ed2dc2e-80ef-4d10-a5e8-9edc3880ba0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5392218a-bc44-4280-a0f7-32eb09030b03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/02-Consultation solde/02-Consulter solde - Chef de zone</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4516c88-9537-4b5d-8ac8-976a1b5b0bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c66c1a89-6a76-4d5f-9055-bdc2693d3f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1e533b4-3552-4336-b38f-a550916a379f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/02-Consultation solde/03-Consulter solde - Livreur</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4aa775-6a15-4e62-84a7-2ebd8ccf8f1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>951ca0df-e5f7-449c-89b3-72b3060ed593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>714d5a9b-7f13-468a-99e5-892de96db79f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/02 - Consultations/02-Consultation solde/04-Consulter solde - Point de vente</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ca5f8ad-cbb6-4648-869b-5cc0e32edfc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa8c63c-774a-4dbc-aa8b-57cf5eedd281</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
