<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoyeur Stock (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a6e1d059-eeea-43dc-8cdb-f2e0d2ddd94d</testSuiteGuid>
   <testCaseLink>
      <guid>16bff62c-3f50-4a8c-9b6a-fa429da8bc3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/01-Menu 2toi aMoi Vaovao/Acceder à 2tmv via un numéro GP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66c47845-6b31-4597-8d40-fb9db1626d6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09a287da-cf6c-45b7-8b03-42c43b6e691b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/01-Menu 2toi aMoi Vaovao/Consulter le menu Envoyer Stock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cea2055-c1b4-4c21-b41d-64faf6ff1ed5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d76a44ed-0324-436f-b11e-343722a8ea93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/02-Envoi stock non abouti/Crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e78b80ef-d1c8-48ad-87c5-89cb7e83fb6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b5f8038-2ae4-4b01-928a-cda6635b93b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0700370-e67d-4ef2-9e1c-845db8a5f208</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>664edb6e-4f12-4090-b6c0-7d78568f2410</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/02-Envoi stock non abouti/Saisie hors propostion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e37f5c-e07a-4787-9450-56ebbad5d034</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d999fc4-2f09-4d18-9dfe-1de01d7e6eed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99e8b7c3-ce98-4148-a750-a2476b74d0ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c7d312-263c-4f34-9db4-03c3d35d6b04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>111bbf98-4755-4213-8f04-41997fadcb2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/01-Envoyer du stock - 10 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5314e35c-fa81-414e-a25a-216dc4215acb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6eeef51-b308-4b28-aa5e-b655852c339f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2109fc1f-34f4-4a8e-9308-79f05004357a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0c52616-b989-4338-8452-c1a42422ccc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba92e976-3f23-4078-83ad-7820d2b332b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/02-Envoyer du stock - 20 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a033a40-b50a-4344-9bd8-1a181e636845</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71498dab-4c83-42c1-845f-6175c5925c8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a8506bd-0c6e-4717-b732-b2b3be0af543</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef04df4c-2924-4e4f-9ea2-55be44715c8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff78d41d-69fd-4f4d-bcda-af00ac5cb218</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/03-Envoyer du stock - 50 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>323e1bd1-4906-425b-aebf-4e87b045f124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db84c095-9753-45cc-9519-76c4898fd94a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10bfe0cd-3876-45ec-85c2-33b1d1092f9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>129c991c-d3ea-400b-8538-c06df729ed68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48e3632f-bcfd-4176-b8df-c09b0c51a477</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/04-Envoyer du stock - 100 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f94c2f-49e5-4f5f-ab44-ff7f20fd3c95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e27d1f7f-dc05-442d-ab6f-573fb5168c1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef5c7b7-fc0d-4477-af32-60e167fdf132</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d74ce89d-a820-4120-8559-965d8cb0a71b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e203abba-457f-4641-9c18-a239294f120d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/05-Envoyer du stock - 500 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15fe0bf9-5428-4da9-a760-26fc5e1d4811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>281141ca-bd75-48ca-833c-f811755f9264</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39facdf8-5966-4626-8399-adc8740ca1af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8befb75-9563-462d-8075-46c270130361</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f68409d3-508d-4391-983b-d62a8217d56f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/03-Envoyer du stock - Montant choisis/06-Envoyer du stock - 1 000 000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dbac98f-95c9-48de-83df-ffd072507f2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361571ae-2c91-4c00-9859-8d7e514295d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b14f12a8-7b78-4401-8136-9ec6021cbce6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e54a975-a9a9-48a5-bdfb-f43368bd2420</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d864895-0522-4acb-b379-7850248dfb7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/02-Envoi stock non abouti/Annuler envoi stock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fa4ef66-804c-4967-a078-2428e4832667</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a94e188d-87e2-4384-8564-1c799269c9b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>004e6521-a7ff-4228-b993-c666552a1982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1542e30-43de-46a0-bef1-a5c75d1ef5e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ed9a1ec-568d-4afb-815d-e5b21983576d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/04-Envoyer du stock - Autre Montant/Saisie montant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81c513ed-e765-4f6d-8cf1-b15ecf92d426</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b34e8049-8b3c-4014-a6a0-95c831cc9725</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/04-Envoyer du stock - Autre Montant/Saisie Numero bénéficiaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b42c73e-2123-4d2e-96a6-a3deddb589c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dabbf748-989a-4fe9-961c-ce1c6d84b923</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2967f35-fd53-4b58-8bf2-c1b463ea4788</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/04-Envoyer du stock - Autre Montant/Saisie PIN - Mauvais format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2746727d-89e7-45b7-bf42-583e56ae63b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f486b12c-88ff-46ba-b389-1f87ffbdce0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0eb43371-8e28-4e66-99cf-db9f2613fea7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/04-Envoyer du stock - Autre Montant/Saisie PIN - PIN Invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cffdc926-3872-46a9-841a-9b7a5bef7410</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c22c9a8-de70-4627-9641-e6d219bd1986</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7198c8f1-79b5-41ce-ab1f-67ee07e11cbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/01 - Grossiste - Chef de zone</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe7d4b2-d579-473d-8e7d-4bb67c89b8d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a604ea8a-0a1d-47a7-921b-b690f12cadb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e76c185-a561-4b36-8011-a5f8b0f47523</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b037195b-1d54-4a11-93b8-54963f6c5ba1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/02 - Grossiste - Livreur</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4261b8b-97ff-4c85-bc1b-149d869bfa98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5763f494-e716-43b9-b125-b35b15af32bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acf1bdf-40e9-4942-a0ce-ab4d05f0bda1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>865ca81d-6ad5-4865-b291-924b654455b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/03 - Grossiste - Point de vente</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b88a3a54-417b-4805-aa88-1ed4b37d09cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8049072-b179-4035-a8e1-8ca94d94c7e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6eb7c21-525e-4ad7-a3e4-2a329b8e3ab2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729ac7b9-88e6-46db-8aa5-9a389b888bc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4382d3f9-88f4-4bcd-9a95-9e628db8dd06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/04 - Grossiste - Grossiste</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5044921b-4734-41ae-9b81-a65f51135be9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17d52efa-5d64-43db-b762-5854dc769b5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abb53105-c07d-4584-9c7c-4d6ff0b7a0de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29d914db-226a-4dc5-9207-cc3a4ab51ff5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97c3c11-fb66-4982-922c-224ba9e2705b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>562fd132-f133-4453-9948-5b2243486ca3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/05 - Grossiste - Client GP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6608bf3-9847-4a1e-9796-bd99c20d3f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7f93766-dba2-4a62-bdce-8ef364bd2318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f5ba3b2-4dd5-484e-a744-d0eef56966e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823dfbdc-cb6d-4b4c-95a4-aad8885bc020</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9e2cb5a-0418-4f82-9442-9029558f6541</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/06 - Envoi Stock - Grossiste/06 - Grossiste - CDZ (Envoi stock inférieur à 100 000 Ar)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ecd15df-618a-4dfa-aee6-7ae39b752c55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd543ebc-7617-401e-b11a-7121b48ddb8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe90be9-5ac9-40e7-a2bb-fd8875e0063b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31213a46-4136-4c73-8e96-b1a91a8fe4ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9849a098-74ed-4e5e-a531-33d154077d80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/07 - Envoi Stock - Chef de Zone/01 - Chef de zone - Livreur</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7352c67c-3501-48d3-9d75-687e06d26c62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9df6ef0-df12-4c3b-9023-46a34a186535</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cbb6f3b-1a6e-4806-b712-5568d890467d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8298ebd4-a3a5-4eb2-ac90-3469569635ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/07 - Envoi Stock - Chef de Zone/02 - Chef de zone - Point de vente</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b42011b1-dd5b-4a37-ae9c-41d604705c16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc0f2149-0651-4975-9f05-c1aac6bbf6a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ccbb198-8b36-4230-be66-e8f27c894db9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c070ebc-3487-4ed1-a1a0-d669cc41eb9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/07 - Envoi Stock - Chef de Zone/03 - Chef de zone - Chef de zone</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f645df-2754-4d50-95ae-2cbbaf94ba06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>942387e8-9fd8-4ce5-920e-2a5d9cd0fa83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad32c45-9651-4e1f-b23b-2afde03a24d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0710dc0-8d75-4632-ba91-d71a8dedd538</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2eb2ab3c-6a0b-4d27-a219-196e6819d73f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/07 - Envoi Stock - Chef de Zone/04 - Chef de zone - Client GP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e957fb5b-5272-412b-a66c-4d2b74435078</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aba5b3da-48b9-4fe4-b394-d793d209d4b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab862380-44d6-4d59-824f-7c5937c5886d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41b53f6d-b9b4-485a-b3ea-58ba21c3c70f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/07 - Envoi Stock - Chef de Zone/05 - Chef de zone - Grossiste</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ba8be7-d1df-4fa2-9eb6-8f35409580b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3934b27b-a4b8-418b-bcc7-5b9795f2559f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8203e390-e710-4199-b8ac-42cd40aaf131</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65f9f1de-b316-4859-a741-a10d20a62ae4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/08 - Envoi Stock - Livreur/01 - Livreur - Point de vente</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f89686ae-acb0-4063-b6cf-63f1f6436a55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d264613-d582-4ca4-86bc-f8db4ffdfc46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d33276bd-93ed-4840-a9a7-5cd96ccb39b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9b7be85-acf5-4c51-932b-ceca592f3392</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/08 - Envoi Stock - Livreur/02 - Livreur - Livreur</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dad5e879-9fa9-418b-ae1a-dc5fcb01274f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc00f658-7831-4829-99bf-2258fd2faac3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc5980f-0420-4cf5-b634-bee023c8ede4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3d2795-db92-43aa-ab74-6c1d52c9e51c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>803cb81b-f41d-42ff-9150-54663d597f60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/08 - Envoi Stock - Livreur/03 - Livreur - Client GP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa182a54-5122-4c59-8893-7092cea81c27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feafb23c-f4d7-4087-bd71-69f4ba3e7273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>411b05f4-58e4-4fa7-beb2-3e02ddcf6c6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a74a331-1d4e-44e5-b0ef-dcf00cd41ddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/08 - Envoi Stock - Livreur/04 - Livreur - Chef de zone</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fed08a76-445d-43f8-a898-2ad6d7cb3d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24b824ef-9f81-471b-8bf2-54c38bf48760</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e266518-31c5-45e2-8531-3453b841fa35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53a81b80-3c66-43a3-afe5-d2236b9248ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/08 - Envoi Stock - Livreur/05 - Livreur - Grossiste</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38fbe48d-7650-4e84-9e9b-d8662820f9f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18789708-22db-4884-9ffb-bc96c4293956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5ab234-fc4b-45e8-b522-02f5a0a17a86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7424cd48-ba55-4e10-a827-c41b7b4e9f30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/09 - Envoi Stock - Point de vente/01 - Point de vente - Client GP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08fd8c02-bb3d-40de-aa0d-bead1d7d03d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f08b83a-7b73-4462-8a7a-0e7e88a1680d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>944c942c-f1e0-4c8d-9e8f-26c426cdaea4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cc732a3-9b2e-4ec9-b46f-bd706c9e3f4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/09 - Envoi Stock - Point de vente/02 - Point de vente - Point de vente</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>016e30a1-5821-4269-8406-32c425be4717</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85065bc8-0052-459c-8072-b4e3ebd6b8cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>328108de-9fa5-401f-84ed-162e58eaeb2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fc5d50e-a72a-41f3-b9b9-93b12aac0a05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55d33680-95ca-478d-8d04-09e1f555d798</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/09 - Envoi Stock - Point de vente/03 - Point de vente - Livreur</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fc2cfc4-f46a-468c-afd5-05dbdd9d8a68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35de6d5-5482-44b4-898a-9c0f5827dfae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37da2d03-5951-46bd-b0ff-af744f376715</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c0a365d-1a73-4600-9c10-65b23507768c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/09 - Envoi Stock - Point de vente/04 - Point de vente - Chef de zone</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f2f4b07-61b3-4809-bf23-3ca4ca1d63fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08f68468-be15-429e-a367-fc00bfb334ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dceb0d74-16f5-4111-94ab-e5a1b7969d2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a6fd7d5-0375-4687-9df5-cbefe465d83b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/01 - Envoyer Stock/09 - Envoi Stock - Point de vente/05 - Point de vente - Grossiste</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>682831d6-4bb1-4d63-8714-c335abbcb545</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96fb2351-4ad5-44e5-b247-766c272339c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa2a68ce-30bd-46de-a200-68a7c552cfd3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
