<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Recharger client (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bd131fb8-4dbb-460e-bf63-115673af43d4</testSuiteGuid>
   <testCaseLink>
      <guid>cd395f41-4240-4adf-ac1f-27dba6f7b2bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/01 - Menu/Consulter menu Recharger client</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fffa82c8-6f26-449c-a8b6-fda0e9bbc313</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b67b5c2c-c544-4127-8c29-6a77fa694f88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/02 - Recharge client non abouti/01 - Annuler la recharge</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>586fa748-98f1-434a-b17b-5c7f7e3ae8c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4754ff-d371-482e-82b5-e35b414907f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>670ec669-1c17-45f7-8ad3-cceb7b6d765b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f333cf7-821e-47b2-96a9-a5e3b4614cbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe83bf69-1044-4b3c-9935-ba9902ca80e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/02 - Recharge client non abouti/03 - Recharger client - Crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55ab46a0-2be8-4156-9936-0e94a7b188a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e890b8-9fc6-4d2e-ade8-12503397250b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ac17145-cc2c-40fe-8b06-d6de7e7991d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ceca94b2-dd58-42c6-be11-03272613366c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/02 - Recharge client non abouti/04 - Recharger client - Initiateur non elligible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a2479dc-9484-4f73-8942-83a284b13554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6dfc07b-5f24-4849-9453-f439aa829910</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0b1c249-867c-4f6e-822d-edee474c3096</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>444c6af1-f9c5-4bf2-bfd4-5a2db0244467</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/04 - Recharger client - saisis formulaire/Saisie Montant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ae581c-103a-4ffc-aa46-08f6fe51d1b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4669b22a-28ae-4721-b561-af48a650b946</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/04 - Recharger client - saisis formulaire/Saisie Numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b375e5a-7035-48ad-8fab-0d30ba51d46b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73d7577b-da3b-4785-ae85-a928335f5d54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/04 - Recharger client - saisis formulaire/Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48a0cd4-b320-48c1-be0e-66c25d5035b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417ce5f4-bbda-4b3d-9ef5-392d01f2c907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c5c415-1883-4765-81dd-807de419fd89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8de8c3f0-5236-4506-a503-e85cfbdb2be6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/01 - Recharger client - montant 1000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b80505e-2770-4135-ae71-3ca76f3b2276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>272ad71a-a3c0-43ef-b026-9c31146823e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5496ce-25f8-4d37-831e-11de374f03ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f0b35d8-690b-4667-805d-38ebb92d298c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ef54fac-60c2-4a28-ba40-1967ae97c33b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/02 - Recharger client - montant 2000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>146389ad-3711-4876-9d41-f21d7522f35f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>850b6392-e968-4822-b0ac-d8fac5468750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd0254f3-9d5d-4496-9f3a-61d17b238f5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f183d03-f9c6-4f49-8037-1b38e3c8c525</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63d0cd5f-156f-40e2-8e36-9ddb6a1fdedf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/03 - Recharger client - montant 5000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d85a0e1-dd92-4790-a9e1-ec5b0f3e6643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34843c11-b17c-4817-9ae9-e4b35eedd79e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39864306-44cb-438b-9ef0-e3138819b706</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28c21aac-8be6-48b2-bf66-fa4e1280fbe5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9be3d739-31e0-434d-abd2-6cdb34e23f5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/04 - Recharger client - montant 15 000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ae98d4d-2f6f-457c-955c-9ccdadc1935d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>610343d4-f9da-456c-9315-4e55d05aa1ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8b91b7-3dca-4ad5-a1fd-fd6a5fd04c21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ec42ede-61a5-4ece-b813-f256f9b48b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a3e39e3-b39c-4509-88ad-36262e744095</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/05 - Recharger client - montant 25 000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fb741ff-7a70-49a7-a517-45a03cbb5445</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8b69482-7e31-405e-8ad6-8e8a29b9a245</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f34af22e-5d88-4c5b-ac6d-682468c567ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0a1428-8545-4d80-b184-195868859607</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e67f36a-36ba-4309-a3c7-0e67c823073d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/06 - Recharger client - montant 50 000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9a0b76d-8871-49a9-b052-aaf6b613b65a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e507cbd-d6a7-4f07-91df-4153129fb25d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0ed873-8421-40ec-9309-4abe75a1f71f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce449729-0f33-4776-abf7-caab3946c804</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcca4533-2234-436f-89f4-2a36c290ff06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/03 - Recharger client - Montant choisis/07 - Recharger client - montant 100 000 Ar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c3286f9-2613-438c-8d70-d6e629ef5155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53708bb7-79d8-4591-ad81-83ae773a2295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def70a22-8fe3-410b-b5e8-64d0b9d23471</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30bc56d4-8bfc-45d2-83aa-b3de6005777f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9f630fb-8318-4daa-92e4-b71c0a2b1d75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/06 - Recharger client/06 - Recharger client - autre montant/01 - Recharger client - autre montant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e49ccc4-cbf4-4f32-9213-451b611e2db7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d102ac8a-e012-4cbb-9483-59561ee5c519</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fde0473-083d-4c54-944e-73b4d0989a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a5c9d78-15ee-49a5-95b2-d44622270e5b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
