<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Vente d hier (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0ea2f036-e4e7-43f9-ade5-2ac715ac08af</testSuiteGuid>
   <testCaseLink>
      <guid>73edcc29-69e9-44f9-87fe-70c4ae30ad85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/00 - Called test case/Consulter le menu 2tmv</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f74f3481-e239-45f0-a53f-4e8ea453a197</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b00dab9-86d4-4a29-a509-c9ca4382ecd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/03 - Vente d hier/Consulter Vente d Hier - Vente existante</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a098b83e-7a5d-4376-8470-622988a8d4c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea4a61bc-74f4-41e0-b901-d36b9e12ae1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d967841-cb24-4308-bc79-0fb562d3d942</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/03 - Vente d hier/Consulter Vente d Hier - Vente non existante</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acc39bcf-57b5-4d62-b0bc-b837c31c12c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21070913-3d9b-4ff7-bc7d-f25356fe5b64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>171b9b74-3f7f-4449-8a9e-9e72fc2b6c54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/03 - Vente d hier/Saisi PIN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ca0143a-b87b-4496-afde-78bba81b3fb4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
