<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Vérification Grossiste (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>810f6779-976f-462e-8b43-e85b1e4ff636</testSuiteGuid>
   <testCaseLink>
      <guid>332f82d1-478d-43b8-943f-5e953985553d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/07 - Vérification grossiste/01 - saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2158f3c9-0dac-4ea1-9569-3b526d34c958</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cae0499d-07aa-4749-af39-e48b0009d017</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/07 - Vérification grossiste/02 - Saisie Numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d3fd07-1c5a-4d18-80ab-f4866bf4fec7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a3f5f5-8a34-4306-9166-15888e1fff13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7889599-1bd2-497c-96f2-7ca8b5f68cce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/07 - Vérification grossiste/03 - Saisie Numéro non elligible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f5f1f4b-3779-45d0-b4de-aef32c6645fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb0addae-fcc1-41eb-97cf-5f3656752a41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c24f148-0ed8-457b-8434-998206f6a852</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2968641c-01a2-49af-ba83-ccca03f0e40e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2TMV/07 - Vérification grossiste/04 - Vérification avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abd23551-c997-40f3-a1eb-d59b817c6ef1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a22acdfb-26ff-48a0-a1a7-f738d8d1e0e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f0802d-f8b9-429e-b39a-703348790152</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ec6e91d-857a-4bd0-92e9-7038eb126bfe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
