<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Achat T NET pour soi via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a21321e8-f627-45d3-b0d2-8ec07e546506</testSuiteGuid>
   <testCaseLink>
      <guid>884dce7b-7079-46d6-a6fb-0b1e5fbd1ae6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT01 - Confirmation achat NET One Night via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a991d97e-8046-4b2f-b281-e45676b2b961</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c727aa-7238-4aee-9e6d-d2d681839b09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf73af82-04b5-4672-9b57-e2fe51f91c79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT03 - Confirmation achat NET One Week 350Mo via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cad1f9b-dff7-4327-af87-fcd04a0b5ac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>232942e2-f823-4900-a24f-8e7f60be3052</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66523eed-5b08-4405-b02f-9029c43d368c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT04 - Confirmation achat NET One Week 800Mo via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40c8613-2b3f-46b0-8571-e8ab78071d7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7783eb-95cb-4a93-91fa-695d1b429694</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c06120b-defa-4a9c-8dfc-b6ad2ad71acd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT05 - Confirmation achat NET One Week 2Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ddb5dec-fe86-40df-ab34-ae0ff6261860</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6af60364-a2d7-42d1-aa08-42da39bb9d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6ca0689-0780-4507-8e04-4bf0040e2aa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT07 - Confirmation achat NET One Month 4Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6711706b-f8af-4bb6-8bef-85a4e0e3fbfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48b8826-eaaf-4b39-b60c-c2bc6986d084</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59974256-2ac1-4605-b90f-99b4b6fb7721</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT08 - Confirmation achat NET One Month 12Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33e4b52a-0756-49e2-9f2b-fbe880898f6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5456e6e2-8dcf-4873-96d6-ed6460180aaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fac0e042-bebb-4214-b378-0312211744bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT09 - Confirmation achat NET One Month 25Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>777af4a3-b0eb-4992-a37d-605198c797c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a87734c-9812-4ef7-a75d-b9894859c261</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cae7e9ba-a0cd-451f-b409-e6e5ec2df00e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT10- Confirmation achat NET One Month 50Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2118b7b7-d625-4ab6-9877-433b7a7dfb47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1233de7-4752-46ab-b11a-b40a5bf81fea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e4d1687-591a-4ad0-b3c8-c61bcc4d86f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT06 - Confirmation achat NET One Month 2Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ded324c-7fb4-456e-90a2-9219f9909aeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6538b2d2-11d7-4527-98c1-2b6edd1eeda9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd63e1cf-b6aa-4795-9a3b-d988cb6b7e19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT11 - Confirmation achat NET One Month 100Go via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91e01bb7-97f8-43e7-96ed-9f8a74f5255c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42b7b9a-c7ad-4f33-9a7a-2deb739347b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>311d2117-8859-47f2-9d1a-2005a5c6193d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/SHORT CODE 611 et 655/Achat TELMA NET via Mvola/SCMVT02 - Confirmation YELOW ONE via MVola--</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4445ad62-cef9-418e-b4e9-ee895d8ed043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e1cfd0-d9be-4dac-a9e4-363fa84f42f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a5d0193-4244-47f4-991b-ddaa90af7f8b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
