<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Achat YELOW pour soi via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f1adf0e0-f1e4-487b-b609-2d0081ea9447</testSuiteGuid>
   <testCaseLink>
      <guid>096d63fd-c861-44df-9a0d-fe97b7e9ea88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY01 - Confirmation achat YELOW 100 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>241c2bec-61be-43d1-9d66-40b8889c0074</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77beb0de-ebe3-44a9-9ba9-93c027690f43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3338f2f3-564b-4055-b895-9e7c16254058</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29e4455f-73bb-41c8-96d6-70cae1b77428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY02 - Confirmation achat YELOW SMS via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8638c5c0-4f7a-4230-92e1-936597293075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e7aa68-eb5b-4bd4-89df-8ddfcf188d63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2ca66e-ce35-4f3c-9fc7-36f139b9f976</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>986d308b-416d-423f-9e9a-f83dbabd43e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY03 - Confirmation achat YELOW FB via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd7e34b6-62fa-4f3e-9ba5-32f830c4b742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7393658e-83d0-41bb-ba4b-b3b6b82e0c88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1c10bb1-3fdb-4f9f-829f-a3cf6a0ef025</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d463d34-e51b-48c9-9c3f-abe3b7f069c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY04 - Confirmation achat YELOW 1000 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d8677d-1ccb-4e7d-b258-42a7317f7914</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>581a5e3a-b493-4a17-91d8-9e5c0c886ef8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f95c492-dba0-425e-bbac-1f77f57d0d48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8183a86c-f597-4d56-8e29-eaea73baa837</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY05 - Confirmation achat YELOW 200 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4faefec8-e0ae-4148-8e2d-bf82757ff31e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>312bceb6-4866-43c6-badc-5fdceb35c36c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9101e3d-3de6-4ff2-ab41-ae61728ef5a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f91c791d-d2be-45ed-b646-e155aea0875f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/SHORTCODE 611 et 655/03- Achat YELOW via MVola/SCMVY06 - Confirmation achat YELOW Faceboobaka via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7384d6d2-88d6-418f-99a5-da36f57ef97b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54ea066c-edac-445e-8750-706f77ea9a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2545d623-914e-4727-8570-577169d939a9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
