<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Achat FIRST pour soi via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>05f1be3c-7602-4da3-a284-00e0f1df5505</testSuiteGuid>
   <testCaseLink>
      <guid>955bd7b9-b86d-48ff-ba57-cd63a6b4372a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/SHORTCODE 611 et 655/Achat FIRST via MVola/SCMVF01 - Confirmation achat FIRST PREMIUM via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be742d2b-119e-4462-8fff-1847e4aa0da0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5abd2f7e-52fd-4394-9c8b-95da2871f9eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37f9fb1f-a288-4be0-b050-db9e9d1735f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73aead49-8896-4902-8bdd-8618e3ee14b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/SHORTCODE 611 et 655/Achat FIRST via MVola/SCMVF02 - Confirmation achat FIRST PREMIUM plus via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c5eeff-4ed1-48d4-badd-819fe76af7e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a336d94-d08e-4b9e-8334-5e40a31ddb1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c6a24e2-9f9d-4c14-af2b-7bb376240027</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c21f4a5-28c4-41f5-81a5-3cb355926e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/SHORTCODE 611 et 655/Achat FIRST via MVola/SCMVF03 - Confirmation achat FIRST PRESTIGE via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9175b4f4-9cd3-4af7-836f-166c7dee62bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8072eba3-d74a-48e9-a18b-2d3e560f1ea9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58d8a508-e024-4894-ac44-67e591036c70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3af1ec23-c039-4b0d-90c9-75334a375545</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/SHORTCODE 611 et 655/Achat FIRST via MVola/SCMVF04 - Confirmation achat FIRST ROYAL via MVola</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ec2912-c362-4536-899b-801a342120bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bedfb7f-e961-45a9-9e2a-3cefab01d8b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a680b03d-5435-4665-9b8d-0d8f74f379d5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
