<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi offre FIRST via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>400624c0-dba9-4147-8182-a64cc0398fec</testSuiteGuid>
   <testCaseLink>
      <guid>70a403b8-c68f-4697-b82c-35e736bc3e3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF05 - Achat first - numéro invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cecb35-67de-45a7-9f3b-6e00cb7e0676</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7c75f64-eb63-44f0-930d-bab97e05421e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF06 - Envoi FIRST- Envoyeur postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31faef43-52ed-4409-a446-18c54645a04f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aa29fe2-7a68-46de-b683-def4a423710e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3d3a893-a355-441c-88f3-a86b53aab115</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF01 - Confirmation envoi FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c4b1657-30d1-4871-8c72-5ee834e2ce3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b897969f-7788-4029-8800-2aa48cac1aa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>091fadc1-2b49-4a1d-9aa1-f119dafdaffb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc889188-5f8d-492c-bc83-cf71da0111cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF02 - Confirmation envoi FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>093e4442-49a0-42ca-825f-2d6b0367a47f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d99121b-e579-44ec-a57b-522317bfc32b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96703d1e-8cb0-4db7-8dce-9a391413c7a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7b52396-58af-4e8e-97bc-87c9dbe6a88e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF03 - Confirmation envoi FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa534121-c480-42c1-9ac3-6af2afd6298f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28ea345d-4256-4947-be35-80018830caa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d878bc7e-0ca6-4a75-a401-2606726505fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f817f67-d233-47c3-b076-ab7dec538a22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/02- Achat FIRST pour un autre/SCEOF04 - Confirmation envoi FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a675e279-9b84-4925-8d13-b73cf512c4c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04f7bb13-f604-404e-be78-2ae3757412e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a894d4b0-c2fd-4130-a508-82bc8db06d8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
