<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi offre MORA via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>187ffe22-0f5b-4558-b9b4-20b0ffcc3930</testSuiteGuid>
   <testCaseLink>
      <guid>a2250747-1116-4ac8-89a0-947091a1fdfa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM08 - Envoi Mora via MVola - Saisie Numero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc256056-df28-4c24-9e30-48dfa234a04f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>addfe9fa-5da4-4e3d-934c-4f9f073a1c36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a65845eb-1da8-4022-b2cf-40ebab04d55e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f4409da-baad-47e5-a876-a1a1b6e67904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM09 - Envoi MORA NIGHT a un recepteur non eligible</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1140b5e1-d961-4568-bde8-0ad2989e1759</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41d13e4f-f5f6-42d7-9115-6224000902ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16028058-57ce-4d05-a2a4-4bcfd86119db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM01 - Confirmation envoi MORA 500 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7eea582-e92a-449e-917d-70b09b7a6642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ca728f-b577-45d5-b6bc-488bd9e4f9ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbcb2746-d287-49da-b909-af5f956a4cb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b354ed9-d387-48af-91eb-49cfc0d26bc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM02 - Confirmation envoi MORA ONE via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a05dccb-4e5a-4d28-a081-a563cc2b72d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f89a8e5f-5b5c-415c-84df-62bf7ed221cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524f0999-0255-4474-8a72-0be2b486be7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91dee589-3012-4ace-b708-dfa8ad9c1ca0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM03 - Confirmation envoi MORA 2000 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fa7c2ff-3dc9-462b-a7d8-574c52923da9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fb14cd3-3896-41a8-9af2-fdfb1509a3bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64908d48-9ebc-4cfe-a795-49ce38a261d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7ad0827-8ebe-4507-beb2-a41359b0f91a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM04 - Confirmation envoi MORA 5000 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af03554b-8bfa-4065-9707-07fbb652ffe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39954abe-9f9d-4663-8132-7d5571814c1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e342330-e7fb-4590-97f1-f7dfba5f2694</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b4796dc-5529-47e6-9f6b-08e587ca487c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM05 - Confirmation envoi MORA NIGHT via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>110bc046-01ac-4845-b62f-80e4e737c585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd1154b-38a4-4722-8961-65ea4b18460e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1ffc01f-baf5-43ba-b605-f1272075bd54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a430e343-d8ac-4c6d-a0d7-037e4c1d4260</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM06 - Confirmation envoi MORA TEAM via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcaccb5d-cbcb-428a-a25d-45f03190f97d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b3fe02-769a-4232-81e6-ccef075fdcf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0071d24b-b8b4-44ed-81bc-d0d7456e6c59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c0f6639-a28b-4f42-8e3d-f7c7aebdc37b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/05- Envoi MORA via MVola/SCMVEM07 - Confirmation envoi MORA INTERNATIONAL via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dafa9e8-b33c-40c6-817e-c5230fa6c5cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6218b06-b40d-4fec-9ef5-3c729299a53c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7595238a-c27f-4e90-828f-ad89c62b486e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
