<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi TelmaNET via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>69819de2-e274-4406-b5a4-54b85a07db3e</testSuiteGuid>
   <testCaseLink>
      <guid>1b989472-32c8-42a0-9564-8dca10f7b7df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET10 - Envoi via MVola TELMA NET - Saisie numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6867273-481b-4cd9-86e9-99daca45d978</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94a41a82-54cc-4f95-adad-b86c919f360c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET01 - Confirmation envoi NET One Night</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abf63f5b-f256-4523-8210-34e37530d053</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a8f47ea-bb43-45d5-a04b-e691808d2760</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c06550f-c39f-4303-b79f-6aea723d7c38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4266131a-3bee-4129-adc0-efa6b7534253</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET03 - Confirmation envoi NET One Week 350Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8112bb3-ad85-4b2c-83d0-5d6bf3d77c89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aad402b-169e-4426-9725-5dcf34552cbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b79a7e0-018c-4693-bb6c-039e90325c06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc0b474a-cf41-4a62-8895-a604091e46f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET04 - Confirmation envoi NET One Week 800Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>809de49f-8c1c-43fb-b8c4-c4710b2f95d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7251703e-2527-4adc-9df1-c94a10197e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbc367a8-eb7e-4454-b383-80d77b80fe8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e098e89b-6596-436b-b748-8ffd082fe0ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET05 - Confirmation envoi NET One Week 2Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a16a75ae-7631-4e16-b5cd-1ab485a7f595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee2a24a7-b467-4b20-8aac-afa4ff0edc98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c32eb2dd-7bb1-41e0-a6b6-bd4236f867ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fa848b0-c72c-4d34-8bfb-660328df6001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET06 - Confirmation envoi NET One Month 4Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7812bf0d-c112-4d04-81a4-034113e10241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06220ae4-7900-49ea-9861-93757cd41287</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669337c0-bff3-4619-b252-439f1f5c3eb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bf848c7-8c36-4456-a357-111fa689d640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET07 - Confirmation envoi NET One Month 12Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba78718-d0cc-4445-aab8-9c04c24e3238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19be58ed-f7d5-4a08-9548-b878b37bb503</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f05e8d9c-3bca-46d1-9b4d-225b5f715cd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dc91967-210e-43c5-ad68-444f7ebe3b40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET08 - Confirmation envoi NET One Month 25Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>485fb4de-35bb-4396-b8ca-e8ef1413e8d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ab976a8-8c71-4d3a-a057-c6b385fa145c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>221e943f-0b47-4f8f-ab7f-201e0013db83</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4f0758d-a6ea-40da-afa3-06f57cc23b69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/08- Envoi TELMA NET via MVola/SCMVET09 - Confirmation envoi NET One Month 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfeb5062-e6be-4b08-b5bf-0a888bfd4015</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86b22519-68d0-41f7-89ca-b1d52db906f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53155797-9074-4441-a551-79167f2a0283</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
