<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoi YELOW via MVola (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3ef47c11-431c-4058-abf2-947c9d320710</testSuiteGuid>
   <testCaseLink>
      <guid>b14eed61-ea81-4a5e-96de-876accdcd4b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY07 - Envoi YELOW Faceboobaka via MVola - Saisie numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52d1f107-7b6f-4d0e-88c6-cd4baf970b8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d620636-5887-4506-a736-ac8860eb4b17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY01 - Confirmation envoi YELOW 100 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ef7f046-bb06-41f2-b9c7-ff70016caf95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaf10279-8055-4e30-a4a6-59c0252b0117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50024769-30e4-4350-9f1a-f052abd8dc79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eec69e85-a770-4244-a939-ec32421221e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY02 - Confirmation envoi YELOW SMS via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dde904b9-990e-4bbf-a281-7bee74cdc879</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694c81ca-d581-486e-829d-e47af0263b04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9cadb10-d148-4fe6-9b9a-65ae6502bdcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79f9d5de-a1fd-41bf-9ea9-5f3245881122</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY03 - Confirmation envoi YELOW FB via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78cd8e6-b63c-47b0-8889-22375ec03c6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af98047c-ff04-4307-b588-310ad5c1a830</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d42a67fd-8e66-4566-a002-1a0b62feb108</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>105c7e9d-6398-4291-bce1-6c2c4a94ce91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY04 - Confirmation envoi YELOW 1000 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef9fe7ef-5cf1-4743-9c3e-760f9273ff9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa9cd01e-7bd4-4a24-9f6e-f08471fdc850</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a541faa1-2ef1-466f-9be4-dac57200739e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>157ded1c-d158-4518-b33f-226e70841b82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY05 - Confirmation envoi YELOW 200 via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b525118-b2cc-4dad-a7b6-5be0f40d5d9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7499ac2b-2ab9-4d23-943f-68e4449e50f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6be6bd34-751c-4665-86a4-e5bb9dc62418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ab46145-0b39-4f4c-bb41-0cdf9a6b5809</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/SHORTCODE 611/07- Envoi YELOW via MVola/SCMVEY06 - Confirmation envoi YELOW Faceboobaka via MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2105ecef-3058-48bc-8cba-24d3f1fa324c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a3fb1b9-4d49-4144-a854-3df3ef0bc834</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fd7a20b-6946-40bf-947f-34ad309c3027</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
