<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Telma Net FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>066048be-5ed8-4cab-b5d4-3a4a9af7bce7</testSuiteGuid>
   <testCaseLink>
      <guid>04933220-ad4f-431f-bb3e-33deabcecb3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bed81070-1332-4b50-9f47-09f11e0dea6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Numero postpaid - Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f5b7492-dafe-4886-886d-171d7c3b356f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06f868ea-006f-41df-a3cd-aebff8cd723f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/01-Consulter menu TELMA NET</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>402f75fd-37c5-44ba-a6e8-2227f1d89c6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70fa3e9a-b4f7-46ce-82b6-39465dd497dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/02-Menu TELMA net journalier</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69bbd9d6-2342-4f41-a0cb-bd3c6f59dd56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b6ed330-f7b2-4628-8067-8c72d1784f19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/03-Menu TELMA net hebdomadaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfa47b04-6ae7-441a-86b2-2eec14642f78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0704ccc2-ccae-44ae-8627-16a598bef02b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/04-Menu TELMA net mensuel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d623a44-3101-4011-97d4-a41990b6e49f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f24ad0c4-0727-4575-b0be-c50d584d3162</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/05-Menu TELMA net payer mensualités en avance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b680bb2-42a3-4c97-b975-22c76f0132bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f7f3dbe-09f6-429e-b379-c34c1c63fc53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/06-Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae3b56d-8ad2-49b2-831e-c8ec56f11c61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb646708-5ae5-492f-b72f-92e8079c47fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/01-TELMA NET Journalier/01-Achat offre pour soi - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342b57dc-f208-41bc-b00f-0999b49cc250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02869407-7221-41ce-a873-027e7a7a521c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1cac72c-c059-49fc-9a66-c78dbef96548</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/01-TELMA NET Journalier/02-Achat offre pour soi- TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6702ca-2fb3-4770-831f-aaf50f9d459d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa0b67b-587f-49e6-a247-fe3cb7554e0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0257a4a-93e0-4ab4-9ab2-10a1f7788381</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/01-Achat offre pour soi - TELMA net ONE WEEK 250 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aa7f85d-cd60-4174-997c-4b2ac716d012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c56e8e31-a3d2-4c03-b4ee-a04025a66441</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a352aa9-e08a-4d0a-90fe-6a6142fdddbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/02-Achat offre pour soi - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c899ea7-c256-4d77-ae67-28c4ae36b50c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfceae20-1337-42ec-bed6-05dddf1949b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>198ed77b-274d-4e94-9b49-f0813a48dc06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/03-Achat offre pour soi - TELMA net ONE WEEK 1,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1102548b-b4aa-4f5d-9497-60e658ee5305</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d7b91a7-42e3-46b9-88b1-41b354287073</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>505e302c-4a2f-41f1-ade2-d11ee0ec94c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/01-Achat offre pour soi - TELMA net ONE MONTH 1,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7167b24f-25f1-4cfd-a784-4bad3e7896a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e6ef065-c013-4bb3-929a-b58a4f455f03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7ab3579-2cd2-44fb-85b7-8e895fe6e83d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/02-Achat offre pour soi - Achat TELMA net ONE MONTH 3Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7ab237-a3bf-4fb3-834d-50da61a910a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64510daf-032b-47c5-8c68-2f479bcbaa0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96b42f10-597f-4d21-8895-10a526bc4ffa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/03-Achat offre pour soi - TELMA net ONE MONTH 10Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2391be7-2f7b-4837-a2ae-747de7832166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>878c1e2a-e0e4-4906-8902-7e20dda65839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>917364f1-d97f-46a3-a0ef-23c8561924ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/04-Achat offre pour soi - TELMA net ONE MONTH 20Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5db05d1-efde-46b7-84b4-981c3d3821f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45556438-c1c6-4ed3-86f5-2c0c1f82752a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>416956f1-6387-4ec1-93a0-ca4dd6b7691b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/05-Achat offre pour soi- Achat TELMA net ONE MONTH 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc48af33-dc9c-4ee0-90c2-5a44ed3703b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61f27092-ac7e-42e0-9ce5-3f7d7d3bbb28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f61cd1c-085f-4ec4-8ce8-2caf847841aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/04-TELMA NET PAYER MENSUALITES EN AVANCE/01-Achat offre pour soi - NET 3 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb9ce55a-d5c7-432d-bddb-762a5e3a5afb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a6e03c3-42cd-45c1-b449-bb495beda826</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ccc8a2b-c322-45b1-9b6b-3b9cd03446df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/04-TELMA NET PAYER MENSUALITES EN AVANCE/02-Achat offre pour soi - NET 6 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cec2caaa-8bd0-4acc-b475-8a5872c0bdea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f00a67b4-36c1-462c-918e-e98fc505ace3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>755e242f-ba4b-4d31-b9de-822e85bd1dce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/04-TELMA NET PAYER MENSUALITES EN AVANCE/03-Achat offre pour soi - NET 9 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbdb8a65-1e4d-4a3d-8872-e874a70870c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6541bd3a-f14c-4397-9189-7174b0359393</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8572e683-1771-4553-9562-61e59860e182</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/04-TELMA NET PAYER MENSUALITES EN AVANCE/04-Achat offre pour soi - NET 12 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad9b593-aa10-4652-a2ad-3daa8a2632be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86f0d68e-5142-463d-a900-45e81f7bf8c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55930f1d-3ddb-4d51-a18c-9182fd3223c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/01-Crédit insuffisant - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>346d6d20-2395-4ef2-9e78-8399f5546de4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc8be55f-6d3f-4989-bd6d-846db860b20c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/02-Crédit insuffisant - TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5063dbea-3b10-4bc6-b64e-0410b8962b79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7ebcadb-6e1d-4f9b-aa53-abb13c3e4f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/03-Crédit insuffisant - TELMA net ONE WEEK 250 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>036aec79-2e7f-46f3-b784-895a80617af1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3728adcd-fcf2-4747-88fd-ba9a565d7e5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/04-Crédit insuffisant - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6608e89b-029a-4549-ab3b-86f37317dca1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29ff6a2b-0fdf-4ae8-82ba-262499daa6d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/05-Crédit insuffisant - TELMA net ONE WEEK 1,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30e78ba5-5ef5-423f-a883-f4fe3dbcee7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>742b5165-b8a6-49dd-9611-c66ef184bde9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/06-Crédit insuffisant - TELMA net ONE MONTH 1,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>814f85b1-897d-4f63-ac4e-29cdcbaf8e9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07033774-03f2-44b5-ad28-d051bd2c7b60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/07-Crédit insuffisant - TELMA net ONE MONTH 3 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db02b877-ce1c-4c89-8911-28f4b9269bc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6226ef84-40f2-481e-8efd-66493d5dec93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/08-Crédit insuffisant - TELMA net ONE MONTH 10 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cc317d4-32ce-4671-8721-db7957eee297</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c97c56a-d7f9-4562-98c3-1c0d6add0fb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/09-Crédit insuffisant - TELMA net ONE MONTH 20 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ff443aa-30f0-4e68-9f55-8763d405e354</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8088d8be-e91b-4d3a-93e5-a1b8af6d7b6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/10-Crédit insuffisant - TELMA net ONE MONTH 100 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abc659d-f453-4f42-b785-4c837bc058e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc21f749-9881-4bf1-857b-c9f439b30e95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/11-Crédit insuffisant - TELMA net 3 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74146eb5-77f8-4c04-b4b0-9bc70de180fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20f3bf7d-14f0-4e95-b97e-31ff2508d7da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/12-Crédit insuffisant - TELMA net 6 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd46ff8d-cc98-4be8-a6e5-996b512d2913</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3aae1935-c448-41ba-bd27-8697b22e149c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/13-Crédit insuffisant - TELMA net 9 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1190cf29-5a53-4e4e-b649-6caf7d9c6fbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c5b9ee1-ad62-495d-87e0-e8c097a879b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/14-Crédit insuffisant - TELMA net 12 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93dc9efc-bb12-4ed4-9d22-50cd22f5f92d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c126962-3f19-42af-bf1a-028dc2956044</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/05-Limite d achat offre/01-Limite d achat - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4da73c4-cf78-46d5-86b3-4e60a0755907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f964b360-fbee-440d-997e-c2291c7912a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed3d1e66-1f5f-4662-9071-8a51cc06b1fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/01-Info conso - ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a1d498-c1f6-45db-97ac-4da33631f31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2174d0a6-3378-457d-bea7-b5143e460466</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/02-Info conso - ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6b50878-8538-45c0-8d71-92b44abd7670</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07f7012e-0b20-460f-9998-eb357f786510</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/03-Info conso - ONE WEEK 250 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>159226a1-e8ec-4d7e-a58e-de9a73308913</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d33e95de-137d-4e81-96b4-64494c9c68ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/04-Info conso - ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ed2152-8bac-4adb-832e-d956737a1fb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc55ab41-dd90-43bd-8460-a6b49ff65e3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/05-Info conso - ONE WEEK 1,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f2a3f71-0ab6-494d-9bf2-6a9027e1cf70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ce342b9-c6c0-4c9c-98c3-74cf0a1bd068</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/06-Info conso - ONE MONTH 1,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0e70613-b987-4935-8db5-aa0fd225987e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7c90dd2-c103-4563-a423-516be4da868c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/07-Info conso - ONE MONTH 3Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6b8037-ffc5-4665-b702-9dfa41558346</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d14d10d4-20e6-496c-9bcd-44ce4ecf01c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/08-Info conso - ONE MONTH 10Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce17dcf9-a795-45ef-887a-d22b79c4835f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94197cb5-6af6-486e-af9c-a446f8126158</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/09-Info conso - ONE MONTH 20Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85eabcc4-0ca5-4755-908b-60c18c78c275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f715ab10-b380-4236-a646-a8b71f22876b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/10-Info conso - ONE MONTH 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc3c27b-ecc9-4eb5-8e17-040bcc5f3c63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>665ae8bd-67cd-4ca5-9396-8748ba31ab54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/11-Info conso - NET 3 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9a6d1dd-68af-4ff5-9519-c51627d1ee35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d4d142b-3a92-414e-a8c5-35d70cb2a334</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/12-Info conso - NET 6 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>652bac27-2828-46ee-953c-a4d1896e258c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>824a9700-73be-42b1-82bd-c28078f630bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/13-Info conso - NET 9 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6da83f9-9d0a-4667-bd53-f9c041eaa64e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5612b825-9840-4fc4-9902-974e90154c3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/14-Info conso - NET 12 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28716a56-6055-4bad-8799-62e70ae3ca4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>342789ff-a6ce-499d-9b28-1a44e446ccd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/01-Etat de renouvellement activé - NET 3 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b63c5e7c-40b8-47a6-8e75-6be554b0d11c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f8f8405-0ae1-413f-bdea-96c8415d6b1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/02-Etat de renouvellement activé - NET 6 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>501c5ca6-c833-4a0c-96fc-01ce9e5a2dcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76bb1759-a24b-4202-8e12-14f6fb814148</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/03-Etat de renouvellement activé - NET 9 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>538dc419-91a4-428f-af7b-ade5a5777603</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71caeb16-f1f6-4cf7-86bb-e7a054ccd704</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/04-Etat de renouvellement activé - NET 12 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee872376-a9e1-4236-be15-a95d46b4138d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a1b52e-5d98-4283-92ff-1c2697b43dc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/06-Désactiver Renouvellement TELMA NET (359)/01-Désactiver Renouvellement TELMA net 3MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b28e93b0-0c57-4bcd-99c3-29efaf8eed5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bbfbfe4-4175-410a-aec3-cb016189cb1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/06-Désactiver Renouvellement TELMA NET (359)/02-Désactiver Renouvellement TELMA net 6MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7639b439-adef-4955-b5e7-428f5aaf1460</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef79d030-3617-4c02-85f7-752f7d50aa95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/06-Désactiver Renouvellement TELMA NET (359)/03-Désactiver Renouvellement TELMA net 9MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a235a0bd-42a9-4695-8dfb-3498cfd2ea1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dae2949-fca6-471b-ab5f-058017d22861</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/06-Désactiver Renouvellement TELMA NET (359)/04-Désactiver Renouvellement TELMA net 12MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e79e1493-bf38-4bce-9d62-93e2cf74e44d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>453d0805-bec6-41b0-be01-665bdf6034f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/05-Etat de renouvellement desactivé - NET 3 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5eecb51-5c68-4dab-a25f-5f60f2764591</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05b1054e-7dac-486a-bfcb-2421af84c3f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/06-Etat de renouvellement desactivé - NET 6 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff6bd7e2-44c7-4894-84fa-a42041bf23ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2095f19f-80dc-4449-b8d7-5bc28e91ff8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/07-Etat de renouvellement desactivé - NET 9 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26b62972-ce7b-4eed-9839-975700ac7a69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afb82c60-e6a0-40bf-8568-091113c69ab3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/08-Consulter etat de renouvellement TELMA NET (359)/08-Etat de renouvellement desactivé - NET 12 Mois</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee66eefd-f30a-4b10-b4aa-8c4c3d57e26e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c7569bb-0dfe-4bc6-a9e2-be3aec9e84f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/07-Reactiver Renouvellement Offre TELMA NET (359)/01-Activer Renouvellement TELMA net 3MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df7dd929-235e-44d7-8655-7ad3ab335dbe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c79d7cc-76a8-4eb6-b151-941298a4fc53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/07-Reactiver Renouvellement Offre TELMA NET (359)/02-Activer Renouvellement TELMA net 6MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e159b95-0a79-4a80-8438-206c7f0fb4b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbaed6e6-e911-474d-b6f2-ec7e0e2fc530</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/07-Reactiver Renouvellement Offre TELMA NET (359)/03-Activer Renouvellement TELMA net 9 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0b5a19f-fbe9-4472-83f2-083f9742379b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d1b1dfa-b1d6-4bbe-a7b3-b8a00c7d1fad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/07-Reactiver Renouvellement Offre TELMA NET (359)/04-Activer Renouvellement TELMA net 12 MOIS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8d28a12-fa6f-4485-84a6-13d4ccdb44e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>303f642f-cae2-478a-8939-ebc027a65df3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
