<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Telma Net FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>066048be-5ed8-4cab-b5d4-3a4a9af7bce7</testSuiteGuid>
   <testCaseLink>
      <guid>04933220-ad4f-431f-bb3e-33deabcecb3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bed81070-1332-4b50-9f47-09f11e0dea6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Numero postpaid - Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f5b7492-dafe-4886-886d-171d7c3b356f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06f868ea-006f-41df-a3cd-aebff8cd723f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/01-Consulter menu TELMA NET</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>402f75fd-37c5-44ba-a6e8-2227f1d89c6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70fa3e9a-b4f7-46ce-82b6-39465dd497dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/02-Menu TELMA net journalier</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69bbd9d6-2342-4f41-a0cb-bd3c6f59dd56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b6ed330-f7b2-4628-8067-8c72d1784f19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/03-Menu TELMA net hebdomadaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfa47b04-6ae7-441a-86b2-2eec14642f78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0704ccc2-ccae-44ae-8627-16a598bef02b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/04-Menu TELMA net mensuel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d623a44-3101-4011-97d4-a41990b6e49f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f7f3dbe-09f6-429e-b379-c34c1c63fc53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/01-Menu TELMA NET/06-Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae3b56d-8ad2-49b2-831e-c8ec56f11c61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb646708-5ae5-492f-b72f-92e8079c47fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/01-TELMA NET Journalier/01-Achat offre pour soi - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342b57dc-f208-41bc-b00f-0999b49cc250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02869407-7221-41ce-a873-027e7a7a521c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1cac72c-c059-49fc-9a66-c78dbef96548</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/01-TELMA NET Journalier/02-Achat offre pour soi- TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6702ca-2fb3-4770-831f-aaf50f9d459d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa0b67b-587f-49e6-a247-fe3cb7554e0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0257a4a-93e0-4ab4-9ab2-10a1f7788381</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/01-Achat offre pour soi - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aa7f85d-cd60-4174-997c-4b2ac716d012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c56e8e31-a3d2-4c03-b4ee-a04025a66441</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a352aa9-e08a-4d0a-90fe-6a6142fdddbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/02-Achat offre pour soi - TELMA net ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c899ea7-c256-4d77-ae67-28c4ae36b50c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfceae20-1337-42ec-bed6-05dddf1949b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>198ed77b-274d-4e94-9b49-f0813a48dc06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/02-TELMA NET Hebdomadaire/03-Achat offre pour soi - TELMA net ONE WEEK 2,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1102548b-b4aa-4f5d-9497-60e658ee5305</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d7b91a7-42e3-46b9-88b1-41b354287073</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>505e302c-4a2f-41f1-ade2-d11ee0ec94c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/01-Achat offre pour soi - TELMA net ONE MONTH 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7167b24f-25f1-4cfd-a784-4bad3e7896a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e6ef065-c013-4bb3-929a-b58a4f455f03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7ab3579-2cd2-44fb-85b7-8e895fe6e83d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/02-Achat offre pour soi - Achat TELMA net ONE MONTH 4,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7ab237-a3bf-4fb3-834d-50da61a910a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64510daf-032b-47c5-8c68-2f479bcbaa0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96b42f10-597f-4d21-8895-10a526bc4ffa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/03-Achat offre pour soi - TELMA net ONE MONTH 15Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2391be7-2f7b-4837-a2ae-747de7832166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>878c1e2a-e0e4-4906-8902-7e20dda65839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>917364f1-d97f-46a3-a0ef-23c8561924ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/04-Achat offre pour soi - TELMA net ONE MONTH 30Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5db05d1-efde-46b7-84b4-981c3d3821f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45556438-c1c6-4ed3-86f5-2c0c1f82752a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>416956f1-6387-4ec1-93a0-ca4dd6b7691b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/05-Achat offre pour soi- Achat TELMA net ONE MONTH 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc48af33-dc9c-4ee0-90c2-5a44ed3703b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61f27092-ac7e-42e0-9ce5-3f7d7d3bbb28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55930f1d-3ddb-4d51-a18c-9182fd3223c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/01-Crédit insuffisant - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>346d6d20-2395-4ef2-9e78-8399f5546de4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc8be55f-6d3f-4989-bd6d-846db860b20c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/02-Crédit insuffisant - TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5063dbea-3b10-4bc6-b64e-0410b8962b79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7ebcadb-6e1d-4f9b-aa53-abb13c3e4f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/03-Crédit insuffisant - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>036aec79-2e7f-46f3-b784-895a80617af1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3728adcd-fcf2-4747-88fd-ba9a565d7e5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/04-Crédit insuffisant - TELMA net ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6608e89b-029a-4549-ab3b-86f37317dca1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29ff6a2b-0fdf-4ae8-82ba-262499daa6d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/05-Crédit insuffisant - TELMA net ONE WEEK 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30e78ba5-5ef5-423f-a883-f4fe3dbcee7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>742b5165-b8a6-49dd-9611-c66ef184bde9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/06-Crédit insuffisant - TELMA net ONE MONTH 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>814f85b1-897d-4f63-ac4e-29cdcbaf8e9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07033774-03f2-44b5-ad28-d051bd2c7b60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/07-Crédit insuffisant - TELMA net ONE MONTH 4,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db02b877-ce1c-4c89-8911-28f4b9269bc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6226ef84-40f2-481e-8efd-66493d5dec93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/08-Crédit insuffisant - TELMA net ONE MONTH 15 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cc317d4-32ce-4671-8721-db7957eee297</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c97c56a-d7f9-4562-98c3-1c0d6add0fb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/09-Crédit insuffisant - TELMA net ONE MONTH 30 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ff443aa-30f0-4e68-9f55-8763d405e354</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8088d8be-e91b-4d3a-93e5-a1b8af6d7b6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/03-Crédit insuffisant/10-Crédit insuffisant - TELMA net ONE MONTH 100 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abc659d-f453-4f42-b785-4c837bc058e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c126962-3f19-42af-bf1a-028dc2956044</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/05-Limite d achat offre/01-Limite d achat - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4da73c4-cf78-46d5-86b3-4e60a0755907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f964b360-fbee-440d-997e-c2291c7912a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed3d1e66-1f5f-4662-9071-8a51cc06b1fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/01-Info conso - ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a1d498-c1f6-45db-97ac-4da33631f31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2174d0a6-3378-457d-bea7-b5143e460466</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/02-Info conso - ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6b50878-8538-45c0-8d71-92b44abd7670</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07f7012e-0b20-460f-9998-eb357f786510</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/03-Info conso - ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>159226a1-e8ec-4d7e-a58e-de9a73308913</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d33e95de-137d-4e81-96b4-64494c9c68ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/04-Info conso - ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ed2152-8bac-4adb-832e-d956737a1fb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc55ab41-dd90-43bd-8460-a6b49ff65e3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/05-Info conso - ONE WEEK 2,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f2a3f71-0ab6-494d-9bf2-6a9027e1cf70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ce342b9-c6c0-4c9c-98c3-74cf0a1bd068</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/06-Info conso - ONE MONTH 2,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0e70613-b987-4935-8db5-aa0fd225987e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7c90dd2-c103-4563-a423-516be4da868c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/07-Info conso - ONE MONTH 4,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6b8037-ffc5-4665-b702-9dfa41558346</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d14d10d4-20e6-496c-9bcd-44ce4ecf01c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/08-Info conso - ONE MONTH 15Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce17dcf9-a795-45ef-887a-d22b79c4835f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94197cb5-6af6-486e-af9c-a446f8126158</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/09-Info conso - ONE MONTH 30Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85eabcc4-0ca5-4755-908b-60c18c78c275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f715ab10-b380-4236-a646-a8b71f22876b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/04-Consulter offre Telma net (359)/10-Info conso - ONE MONTH 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc3c27b-ecc9-4eb5-8e17-040bcc5f3c63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>303f642f-cae2-478a-8939-ebc027a65df3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/00-Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
