<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Recharge FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>91cf888d-1a13-4dc3-bbe2-eeed47c586f8</testSuiteGuid>
   <testCaseLink>
      <guid>d4121ed8-501c-4551-bcf6-5f9e403148fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Menu Recharge/Consulter le menu recharge</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76473688-ab7b-4f52-9074-d1c8d78cd749</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1f02e8f-c6d0-4a16-8d01-079cbc882e10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger par MVola/Consulter le menu recharge par MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a449843c-f86d-4bde-94dd-fc88c371c2af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>060b1121-b9ea-4965-b055-590f0408f34e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/02-Saisir code de recharge au mauvais format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>981ab335-34a1-4454-9b57-0dbc85977c54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9262449-7788-41a2-ad6b-8005f0d19993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/03-Saisir un code de recharge inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0c20c8b-6039-4a22-8ce3-70b8d4ae3303</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc76e80a-cd3c-435f-a237-4d6ea68c82df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/05-Recharger - client suspendu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>592c92eb-56c7-4c90-92d6-1569d2b301c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>555df15e-a3c7-4045-bc71-217ef7c53097</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e276f171-7ef2-4003-a5eb-795da3046048</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/07-Recharger - client postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8475df17-b6d5-4d1c-afd1-69fbc45c5b4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>225ea32e-d241-4cae-afcd-599b5ef841f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/01-Recharger mon numéro avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4468211d-9356-4c29-a2c7-7d0c5911756c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbdd5e15-c6b1-4583-ab2a-e0383a71b06c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282a491f-7d46-4fcc-81a9-49c1ebaa186c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11e1bd0d-cef0-4d8a-9d7c-478eee77bd44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger mon numéro/04-Recharger - code déjà utilisé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a6bdae2-4081-4bc6-bf26-5077ddcb023c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4caff0-b9bd-4c78-98dc-804f961e72ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71d7a0e9-d13c-4f93-9600-925cd65a5d17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/02-Saisie code de recharge au mauvais format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58347a6b-87d2-430c-8543-9196d035a164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed590ba2-bcfc-4754-8701-ad758bb60c41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>564a6f0c-d41c-4491-9494-e0cd70a509de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/03-Saisie code de recharge inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aece5628-5d4e-494a-bc2d-866feabf114f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdf40e35-05ac-439e-8e8f-8de03f3dd312</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88225a15-f511-4092-833f-1264b82bd220</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/04-Saisie numéro du benéficiaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66b39653-070c-4604-a189-b22b5accb321</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e576753c-19ec-4f92-9239-3b60def02368</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/06-Recharger - client envoyeur suspendu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96fb5ddf-2485-416e-91b8-b33513d3018d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdf999af-47d1-42a1-9186-f4c39833754a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e67c2b8b-e6ab-4fa5-a17f-4a4b2a31926f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14bfa792-a527-4989-b6fd-23cff1d81c74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/08-Recharger - client envoyeur postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d4ec31-8ee8-4dec-959c-d1e09f65d95a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6292ffc-fda0-4369-854f-3f66e5690ea4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/01-Recharger un autre numero avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6367200-97c2-4869-9646-d16e51c5ad0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f43f959a-65f1-4a1a-b294-83803946e2d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adca809b-7906-4b39-a784-2a1ad4438bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07c53c0-a188-49e7-b207-e03ace62789b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f231f5a2-e2b6-427d-a8c9-29f0226babc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Recharge/Recharger un autre numéro/05-Recharger - code déjà utilisé</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9aa8df-3f6e-4709-a742-dfd8d69a0ff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a008b09c-d752-45ac-9452-42a5727ab395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19fee979-e604-492d-951a-315f0f8652c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8038cebf-4c0a-4bb7-95a3-69c04c359982</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/00-Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
