<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>demo ddt</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>85868ccd-951d-46f2-82df-9beb1c76be87</testSuiteGuid>
   <testCaseLink>
      <guid>ca8cfa5b-ccc1-4b10-a936-0697eee4d50f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/zz - Demo ddt/SCMVM01 - Confirmation achat MORA via MVola</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86c96855-03c0-4def-91d5-f73bde9cfc4b</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>4</value>
         </iterationEntity>
         <testDataId>Data Files/demo ddt</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12bb809b-9ef3-4172-9dc9-53e0d2b2f62c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bfd633c-b459-4339-a00a-fda77b3db456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86c96855-03c0-4def-91d5-f73bde9cfc4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>montant</value>
         <variableId>cc3b1398-24a6-4ff1-81ff-669068f21c42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86c96855-03c0-4def-91d5-f73bde9cfc4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>offre</value>
         <variableId>ac0e550f-3d83-4afc-a463-d4ff52059635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86c96855-03c0-4def-91d5-f73bde9cfc4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tarifCode</value>
         <variableId>673e43c7-d17e-406d-8176-ddc9c6952dc0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
