<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoyer Crédit (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>922ce19c-912a-464a-8075-62b80f19e4b0</testSuiteGuid>
   <testCaseLink>
      <guid>492729e2-0e99-4e02-a36b-8112d57a44e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV01 - Aide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ac29e4c-c815-4039-ae7e-1ceb9700dff3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdf46834-a685-4699-a382-dfb04867193f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV03 - Saisie montant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974f6e82-b15a-4c54-a679-26ed1a59b2cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a70c142c-fdd3-477a-9842-46ac32b3dfc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2bc8231-6d5b-4835-81c1-185748fa1a10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d56e656-0ea8-45b9-ad97-3ed89c2993f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd7cccf7-1577-4b7f-96e7-6b6aa3349593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f33c7a1-147b-4850-a83f-aec43c3f9e93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV04 - Saisie numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcf96e90-2120-44ec-8fa6-683527642615</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b868f955-7a36-4143-8ad6-d4db3726da1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1810cce-9417-42f9-a2a3-627ee936c619</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cafc12b5-0e02-4057-bf16-b87fd261f3b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4de3e59-11e3-41eb-a58b-9f0b9d6633d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7926ac92-f106-40a1-86ca-5d986bf67037</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV05 - Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d064f27e-70a7-4c6d-8631-e553848acba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>035b565f-1656-46f8-a141-aee410661243</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11aa0ebd-6e20-4f3d-a932-ba7c1fa51611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28cf59f-aee8-4922-9489-405ae48652ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd31600b-2c45-4cb7-b859-3d2c1478e6b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cdc4140-bea4-4416-932e-b3a9fc2941c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV06 - Crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5406aabc-406d-4e82-8e93-ae1fd2742015</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e22869-fc86-4a87-935d-7b825efd393b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e0d91fa-a4f9-4195-a65b-86eff5273587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79dae2a8-6fb7-455d-a129-3f007ed4b924</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f4c6fd5-f7df-4a0f-998a-28b57870b667</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abad0309-be5f-407d-8316-b8cc151a38f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/SHORTCODE 634/SCEV02 - Envoi crédit avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1d1cd01-f9c0-4844-8f54-178862bce755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d48010e-f4c8-4c97-b768-c413b653a4c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfded851-46fc-482f-843c-6dcb5fe86ed4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79d27af8-af38-4b40-aa7c-2bf631c93cec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab2b1754-0d45-4f29-bf5b-0833e8c5c690</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
