<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Friends Family (FR)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b15540f8-2eac-4a8b-ab5d-e5fc5e80f4eb</testSuiteGuid>
   <testCaseLink>
      <guid>47732015-4811-4110-ab65-50dc40713115</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF01 - Consulter menu FAF</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>223fc841-2b41-4b63-8d51-6a56e9eb02cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efb865fe-bae6-4b9e-af84-1d2195a8697e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF03 - Consulter liste vide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aad7c2da-20ca-4257-840b-4c0eca5840f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51e764af-70cc-41ed-8794-bbc0b7930ce0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF05 - Ajouter un numéro invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71d2886-7955-47df-947b-efd99f33bb69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d1b49cb-f01c-4507-ba8e-cb2c44c69871</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF06 - Ajouter mon numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcea4926-da73-4a47-8af9-3d2c226ecb55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dde63deb-1d72-41cf-bc4b-56fe47305547</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF09 - Menu suppression numero</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab7f590a-456a-49af-afad-d86f21efe4ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebef6d75-4b25-4b93-9fff-f67e9b654e88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF11 - Supprimer numero - Liste vide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c076821b-8fed-4791-9611-d1c82ebed10c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f16ed467-02d2-4e04-a8a6-89c124ffe289</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF12 - Supprimer un numéro invalide</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c31b7b6c-537f-483f-bdcc-2997cd8525ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>582ca031-3908-4508-8cf6-f04febd2f63f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF04 - Ajouter numero FAF</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>044901fd-7302-4673-958d-b39a3d503bc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80d9da2a-3ec8-4ee6-bee9-fa9912070fe2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a897f241-8e16-40e1-b989-40d9e79df1e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF07 - Ajouter numero déjà exsistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c441de1-4517-416a-9cf4-133c2025f381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b1d10e6-459b-4f29-b39e-d69af13be6b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d46304cd-3fe2-43e6-afc9-a8d7270dc531</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF08 - Ajout - Numero FAF atteint</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93e4dacf-fdd0-4218-a0bd-ea017fce378c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5e0340f-7b0f-4577-a271-01e844efcc40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1edade5-b5c4-4024-b862-ad041cdfe85c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e03a0f6b-c467-4439-8400-ffc5b56c523e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF02 - Consulter les numéros</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b089ff8-438a-4798-ad5e-38893025ebe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cf6ed3c-292e-4166-8751-c1e2520dee6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed4cb633-25f2-45e5-9e5f-f0d6d38b0517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b34ec1c-3954-47c5-bb28-8f99142efb5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>348e613c-6d7c-43cf-95f1-47b23f714283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Gerer Friends and Family/SHORTCODE 644/SCFAF10 - Suppression numéro</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a8b7e9c-fcd9-4fcb-97d4-86e434f28681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49131980-3b3e-4460-b1b8-672b8097b6ce</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
