<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Promotion TELMA NET MG</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>20284945-d112-4baa-9a91-cf568845ede6</testSuiteGuid>
   <testCaseLink>
      <guid>73158f92-3f6d-4ef6-840d-6de7451328f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Numero Postpaid - Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75383939-df7f-4178-8590-13fbb27e8c80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>285dc90a-9c00-4eaa-ba32-44fd9eb280a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>addfd61d-5b8f-4614-87ed-a40776fa28d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e66e766-c9ce-42ff-8971-afdaf0cc65b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/01-Menu TELMA NET/Consulter menu TELMA NET</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92150e4-9049-45f2-b9cf-641315a2c32f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4daee11d-211a-475e-a071-c5b508d38eab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/01-Menu TELMA NET/Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4fd445f-ff9b-4f33-93d4-8c47c3b3453e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a0fc964-9a15-4d66-a620-ae8a983c6592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/01-Menu TELMA NET/Achat Telma net erreur de confirmation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5e2863b-4e42-4da4-a136-2b3675537981</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54e5c76b-2095-4fd4-986e-e89e2d8e6ed0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/01-TELMA NET Journalier/02-Promotion - Achat TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bcbde4a-936c-4805-8c5a-6d70c7323ba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d248ba0-6e5b-4609-8314-4b6cbbfbc8b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb621fba-6006-4e96-bb88-da254115f129</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/01-TELMA NET Journalier/01-Promotion - Achat TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0474a22-faf4-44d4-9be7-07ffaf7c781f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>106c4de2-b1ba-40ab-b4d4-1ec822b4b823</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa39201e-2ebb-4be1-9358-d9cccbc3283a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/01-TELMA NET Journalier/00-Menu TELMA net journalier</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0779af4-1e55-49d5-a19d-af1c0ce35781</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bc4bb04-7dbb-43f6-aab7-13c69f860bec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/02-TELMA NET Hebdomadaire/03-Promotion - Achat TELMA net ONE WEEK 2,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a631a5-dba2-4111-b5b3-5f645d3aed82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb4b9ad0-07c4-4765-bb76-59a0bf4263ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59a46432-34c4-4a49-9768-e4bd0e7f4701</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/02-TELMA NET Hebdomadaire/02-Promotion - Achat TELMA net ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b55f321-a79d-4dc3-b8a5-be081653b020</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efb15fd0-dc7f-48ed-ad06-095f5e734adc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2ecc0e2-8ff5-454e-b86c-e5a8d9748756</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/02-TELMA NET Hebdomadaire/01-Promotion - Achat TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5b3f424-47d3-4e3b-a33b-79fcbe3a2922</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e26de2bc-50b3-42e4-b2a8-0e1455d5fd7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adf7cd86-2180-43cf-b3af-2a4444a8f96e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/02-TELMA NET Hebdomadaire/00-Menu TELMA net hebdomadaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11f57b0a-0bf4-47ab-894d-5fb563f42af3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>188a0b78-2380-4da8-9d10-6b8a74dbd470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/05-Promotion - Achat TELMA net ONE MONTH 100Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec1d893d-87fe-4830-80db-af5f6cc36094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b1e8f3-0f38-4e4a-a642-0b3132649ca8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3e69858-8c34-4057-a3ed-2e2497e53403</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/04-Promotion - Achat TELMA net ONE MONTH 30Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b18b842d-cac1-42a4-ad4b-8e80c3bfc1f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c146448-616e-491a-a72b-b99b3a48a6cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff7f4b3c-6b6e-41f6-bbd4-77d08ff7299b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/03-Promotion - Achat TELMA net ONE MONTH 15Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fa47443-efa3-4f1a-b83f-c186b0053712</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fea7b58d-5add-4cb7-90a9-c5f2976e3cf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a550e193-f391-47c0-8c92-4acc70a10465</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/02-Promotion - Achat TELMA net ONE MONTH 4,5Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b1ee350-60a8-4e86-b528-4ce125e10454</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c100799e-45cd-440a-ae1d-41be56081ace</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b552e65-2c9e-4745-8072-9a0f3a1ffa2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/01-Promotion - Achat TELMA net ONE MONTH 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e3621ff-9803-4e6f-b493-685ff737bcee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3723754f-756c-46d6-9733-d17d098763b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb2f46fb-c659-44e2-969e-275238ac420a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/02-Achat TELMA NET/03-TELMA NET Mensuel/00-Menu TELMA net Mensuel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b51d1a2c-6782-40c0-969b-4b4180236857</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7471a5a-3661-41a8-bc34-bea0d63fd8b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/10-Crédit insuffisant - TELMA net ONE MONTH 100 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e791a2af-15a6-41e0-9e76-be197cb547fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62e5fce6-367b-486d-bd80-37ea50c6bfb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/09-Crédit insuffisant - TELMA net ONE MONTH 30 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f2ff37d-1aea-441e-910e-0546323d4b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>109db76c-abb8-49c5-bc33-c8f3de8d6cc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/08-Crédit insuffisant - TELMA net ONE MONTH 15 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5489041-7450-4bdb-87aa-4a01efc78b18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>517c17d5-2e8d-42b6-aad5-59980c050f94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/07-Crédit insuffisant - TELMA net ONE MONTH 4,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79cefba0-3791-4c61-b623-3a5a58eff6f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>375dbbac-e596-4bf3-b666-fa24536ebf77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/06-Crédit insuffisant - TELMA net ONE MONTH 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22cee445-ff5b-4fb7-be9a-b9863b6bf8eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>526db39f-f0fe-4a9d-a512-3112e11b83f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/05-Crédit insuffisant - TELMA net ONE WEEK 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0c6c252-3418-48b7-8140-5414f01b61e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>629e874f-c97a-45a5-9363-79fb942eaeef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/04-Crédit insuffisant - TELMA net ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>088f6929-5bdc-4673-b266-e94ed7263773</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>212104ee-e427-4504-aebf-72069b7cd512</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/03-Crédit insuffisant - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056315b5-7b0b-4ec9-87e8-4c935fecdc88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef70ea03-1dfc-4cd8-bb33-3395d5471f95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/02-Crédit insuffisant - TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5062fd20-b530-4a57-a899-578241a2decb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8875a64-c6db-440a-8b32-20057bbd61fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/03-Crédit insuffisant/01-Crédit insuffisant - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa257f18-0cc5-4c4e-bb65-68d5014fa855</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd7a94b9-dca5-44cb-a96d-aaf237c1e036</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/10-Annuler achat promotion - TELMA net ONE MONTH 100 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>403c5dc8-2dff-4afc-b5db-5fcee193e727</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9a74f8f-92f5-407b-88e2-2cb6b18454e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/09-Annuler achat promotion - TELMA net ONE MONTH 30 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a5d289c-d257-45d5-8d2d-3d210b135c64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>625a4212-cdfe-4b8e-b9a3-921f6b67d076</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/08-Annuler achat promotion - TELMA net ONE MONTH 15Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d296c549-a8da-4266-b34c-5f7f19b7c06f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2df712ee-1ae8-4114-a767-2d5ca95abc40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/07-Annuler achat promotion - TELMA net ONE MONTH 4,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dd5d379-6d44-4cfd-81c4-9c9ae970b547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>560f6dac-1ab9-4342-b61f-3cb4e6e0c39d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/06-Annuler achat promotion - TELMA net ONE MONTH 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8731becb-202d-4d56-a791-25bb8691bf8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b4a9eba-820b-4aff-9719-21f46d76ceb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/05-Annuler achat promotion - TELMA net ONE WEEK 2,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>620359be-e9b2-4b3b-8cb0-7fe9261dc019</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0da2cd9f-7330-4690-8b13-6768341f66f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/04-Annuler achat promotion - TELMA net ONE WEEK 1Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee33158-a4f9-4b62-822e-43dbc7910b1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37e3f989-6ee6-4cda-b8ca-cede950016c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/03-Annuler achat promotion - TELMA net ONE WEEK 500 Mo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef510dc3-88e4-479d-9fd9-f03b0cec14dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47d74592-b368-4b5a-ae97-53bbd4656b9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/02-Annuler achat promotion - TELMA net ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aef47aa6-0657-4c7d-9e8e-bc8aeaeebf10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb085a4c-b8dc-4332-ae98-e683786fc9f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/05-TELMA NET/04-Annulation Promotion/01-Annuler achat promotion - TELMA net ONE NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9037a964-8bb0-45aa-ae43-1418ad0c7724</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac3e5623-cd61-47d9-bb6a-c1035a38bd8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00-Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
