<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Promotion MORA FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c7cb22da-f004-4359-8f83-bd5e10f29350</testSuiteGuid>
   <testCaseLink>
      <guid>18f84904-0a86-4918-be39-516b36df8662</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>addfd61d-5b8f-4614-87ed-a40776fa28d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bf7fd7a-926c-4e92-87bf-528f8972e9ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Numero Postpaid - Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75383939-df7f-4178-8590-13fbb27e8c80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>589b09aa-2528-4293-8a78-cdaa35679b5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/01-Menu MORA/Choisir un menu offrre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a24a170-bf03-48b3-939e-ead8a76b62e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d1206ff-daa9-4d14-8434-195b681062f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/01-Menu MORA/Consulter Menu MORA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07c8e22-109a-4605-9ee8-d165b47d608b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39b495b7-eed7-4295-b0a1-ce7ef28e193a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/01-Achat MORA pour soi - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c630671-2e74-4c1a-9501-4e368312cd8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca11591e-7c52-47f3-8041-bd4bea5c41ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf693cf1-67c0-4dd7-bf02-5708ca0dd6e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/02-Achat MORA pour soi - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47511769-a651-4ca8-98b7-9bbbb2bf8469</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d757249-f6f1-4f7c-b5f1-a27109c45af3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea1f552a-c6c8-4ba6-b215-35f2ce28cfde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/03-Achat MORA pour soi - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118dd681-69f4-4871-877f-fb3c8df6577e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4782f16b-f5fd-454a-97db-cbe549adf274</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ed04d78-5e42-46b9-b3dc-245c46391b48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/04-Achat MORA pour soi - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b268030-74f4-48a9-b642-eaa11dc32990</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a85e559c-cee1-4e4b-a392-c048a66404c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aeadd855-f330-4607-81b8-b464cf22dd25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/05-Achat MORA pour soi - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d43f353-95c0-4b44-a2ba-389c26c115c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a32a386-0c55-40ca-a1ec-b8d84fdf593b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa701e1e-a39c-46b7-8371-d6d6a4418de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/06-Achat MORA pour soi - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0913bf3a-401b-49e7-b3dd-453a93c050bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5582f5-3b5b-48c3-8410-d7c69b2fb6c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8a08747-5bd5-4120-bdf4-cfb388a5cdb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/02-Achat MORA/07-Achat MORA pour soi - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d9d51b3-f58a-4a71-b465-45d8aa3fb703</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12b74644-2996-4a80-8855-0b20199834c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b94592ee-af21-4f58-8558-fb40c8272707</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/07-Crédit insuffisant - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68547bdf-1d95-45ed-b2bf-76822eeb0ff7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be2f75e7-5476-4ab2-b5ed-0cec79803a0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/06-Crédit insuffisant - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03aebdac-0567-42a3-be22-b9072950eb65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78ae221b-fac2-4461-9627-0ab96c9b82b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/05-Crédit insuffisant - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61475a39-a08f-4a1b-b04b-76791753422c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>614f8968-dbd3-4b4b-939d-69cda21b908d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/04-Crédit insuffisant - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a878ffe-efa6-4148-8040-24fe066e1357</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>775ca852-e96f-44c5-a058-c0527c33f6b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/03-Crédit insuffisant - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84018ad6-6e8f-47bc-b7ea-9237737d8cad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e457388-662f-4545-9fca-d66bc1df01cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/02-Crédit insuffisant - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9255ff2a-8907-4adf-83da-ddfe45c6408f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>484ad49a-a177-4b05-8760-6b5d656f5163</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/03-Crédit insuffisant/01-Crédit insuffisant - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51ae79b5-b8af-4165-bc55-23f6b1ec1173</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bcb269e-57d4-4079-b119-dcc3c52ce3c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/07-Annuler achat promotion - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bdea39a-1a5d-4b77-808e-e1ff8d961184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22db778d-5160-446c-9d66-735aa81f3219</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/06-Annuler achat promotion - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22ea28e2-ab4b-4a0f-adb4-8119b82838e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a350ed65-86f2-4cb9-bfdb-2d7fa4eb50cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/05-Annuler achat promotion - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b8ba079-6a44-4ff2-a3f0-9a53292bcd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8e753e5-dc3f-4ad2-a60f-5551a53ad4ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/04-Annuler achat promotion - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a052115c-fe84-4a6c-9cd7-863140f06323</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb42890a-7810-485e-81ab-4fb5adcff5d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/03-Annuler achat promotion - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0afb1cc3-01a4-4b8b-9c46-47c6e10373d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e035573-764f-4ad4-9260-6c97cc704704</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/02-Annuler achat promotion - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e8d51e2-4fff-4d00-a97c-e4e763b03c07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ad08be0-faa8-46f7-8d2d-b8996c0ba3f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/02-MORA/04-Annulation achat promotion MORA/01-Annuler achat promotion - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3688b709-ff8a-450e-ab08-5c6ad18928fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39e18858-2df6-4900-9f5f-8864da6fad1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
