<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Promotion FIRST MG</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>42a3bd23-847f-4efb-b338-969ce7da3741</testSuiteGuid>
   <testCaseLink>
      <guid>d2ac680e-33af-44f9-91c0-a857ecd862c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>addfd61d-5b8f-4614-87ed-a40776fa28d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d977f623-778b-4838-a113-24a746eab265</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Numero Postpaid - Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75383939-df7f-4178-8590-13fbb27e8c80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>264272f8-447a-4ef5-90f6-52e1af182426</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/01-Menu FIRST/Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>541828c5-1df4-401d-8d5f-2cf0f0617362</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b05cc6a6-4392-47e6-b6a5-6fc70051011d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/01-Menu FIRST/Consulter Menu FIRST</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a77747c-b08a-47a1-b768-90dcf525e42b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26e4c185-ca0b-49d5-989b-19f9998c8cc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/02-Achat FIRST/01-Achat FIRSTpour soi - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2643826-a8bf-4991-a8ae-79d836cf5506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e994498-2af4-45b2-9b1e-6cbe269e12c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>476a34b7-38c5-40d1-942a-7b093552870f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/02-Achat FIRST/02-Achat FIRSTpour soi - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17870ca-b73b-4bec-93d0-c2dc88e34a3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70f64aa6-7743-48ac-9a90-515348d47a29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4d17c55-ae11-4bc4-a563-c7535206b4d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/02-Achat FIRST/03-Achat FIRSTpour soi - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33dc242e-e44e-4867-b9ec-baaf5a7a5969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a556f0f-7db2-4c7a-8a28-5ff1c319a118</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbb15e68-f7f7-48b1-832f-2c616ef8432b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/02-Achat FIRST/04-Achat FIRSTpour soi - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2f6bf9f-ac46-49d8-af3f-48d307cebafb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>214e2171-258d-4b68-b899-bed15fb62c5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80631bc4-b01a-4f3c-ac66-587822f6e576</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/02-Achat FIRST/05-Achat FIRSTpour soi - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a1f1ba-2568-4c65-bca6-8352604aee0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccb4989b-a5cf-44b6-9858-a702d034d354</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f30059bb-6cd6-4a79-9909-eeca056458fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/03-Crédit insuffisant/01-Credit insuffisant - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dc89626-08a0-40d7-b197-6e1d6bca553b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69e1c4c5-891e-4e0b-a3ca-e6953977828f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/03-Crédit insuffisant/02-Credit insuffisant - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>308a9756-4d9d-4977-9bbd-4d1047c493b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1babadf-9079-476e-a066-f6b49b0cf77c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/03-Crédit insuffisant/03-Credit insuffisant - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>206070d9-cacc-4764-b7a8-0b7d634da22b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06b078ce-36ef-4664-9eea-bd71500559d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/03-Crédit insuffisant/04-Credit insuffisant - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1792d525-8226-4a2d-b5a6-5404774c731f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0b3b1c-dbc1-4839-8a43-f384bace5455</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/03-Crédit insuffisant/05-Credit insuffisant - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7b312b-2fcb-49c4-bbe6-24efacc43b6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eb8b80b-7bae-4697-aabc-115789dbee85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/04-Annulation achat promotion FIRST/01-Annuler achat promotion - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c692ff9a-1fd8-476b-a7f4-24ef2ec923e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>419991b4-479d-4a10-94f7-74fc28e9b74e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/04-Annulation achat promotion FIRST/02-Annuler achat promotion - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>432acd23-bd6c-4d8f-b0c1-ab2b91f88604</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ba9ef8c-7ff2-4a3b-aa4c-6f41bbe672d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/04-Annulation achat promotion FIRST/03-Annuler achat promotion - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0ab55c8-cc26-45a4-8dc2-a53628abea6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61c6fb00-ff17-499b-a49a-7223c884bc89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/04-Annulation achat promotion FIRST/04-Annuler achat promotion - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a689e23-a18c-4d6a-b018-a61918be599b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7371e53-a2cd-4d0b-8ac0-2d0992e2dcf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/03-FIRST/04-Annulation achat promotion FIRST/05-Annuler achat promotion - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098a9798-25c4-4ef9-8bd4-40ba9a18af1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9d399b4-bd1d-4a81-8341-a6768d4b7eea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
