<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Promotion YELOW MG</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>89a87765-7f92-4ab3-8d78-ad002e99c460</testSuiteGuid>
   <testCaseLink>
      <guid>75d14ecc-19c3-4867-8ebb-94dd223ae32f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Numero Postpaid - Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75383939-df7f-4178-8590-13fbb27e8c80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f5b4d8e-a2a1-4a6d-b333-33601988a2b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/Menu Promotion/Consulter Menu Promotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>addfd61d-5b8f-4614-87ed-a40776fa28d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3fd1b2-794e-48da-bf79-402e559df295</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/01-Menu YELOW/Consulter Menu YELOW</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe1c6ea-602b-4588-9221-0ade5f0d2202</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca02777d-9ce8-4169-b8d6-7f026a5d0f66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/01-Menu YELOW/Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab7d4690-8059-4d4c-8a3c-4765dd89569d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>169ffab1-f996-4144-b9e4-660168c8b732</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/01-Menu YELOW/Achat YELOW erreur de confirmation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e32daf53-3413-4b95-a6cb-6dbbe0e4a6c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ac1a3e6-1941-4a87-8e55-820d41974a1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/06-Promotion - Achat YELOW FACEBOBAKA plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62e6e388-5035-4ec5-8164-11b06dadc904</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e117a73-1c20-41c5-8510-e79656389fd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5abcada-4443-4dba-884f-e39ebbadeb2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/05-Promotion - Achat YELOW 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0d7c6b-4c7d-4260-902b-b2d3d988a6eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d180d48-7692-4577-85f4-a9058603d0d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80698c4e-05f6-477d-b957-339d315cf87a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/04-Promotion - Achat YELOW 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3651cd3-33d7-4b0f-8338-8e32590e4a37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4a23399-7ee7-48fd-aa45-73548e06b7ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20a935b3-b131-4f29-974b-50bece400577</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/03-Promotion - Achat YELOW FACEBOBAKA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b410790-f665-4463-b50f-205cbb3800fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89d180ee-d06a-4b36-a550-9dae72961c48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18182432-26b3-492f-8e04-32b2f39bf0b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/02-Promotion - Achat YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe33b16-756d-401e-8dc7-887e71aff55b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2e473c1-cbbb-4a31-b68a-296710b93eff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ee2882e-b66b-4cd2-9eff-69ad5587fee7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/02-Achat YELOW/01-Promotion - Achat YELOW 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4a4acaf-122b-44ea-b63e-4f4d7553fe96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b54b77e-2da8-4bdc-90bd-6e9db2d81ea6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f764df4e-917d-4e9f-a869-ca9ef1439b90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/06-Credit insuffisant - YELOW FACEBOBAKA plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c2f48a0-b415-4df0-8146-573c09ce3d3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30616f70-c984-497d-8bff-73e8cd78cc37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/05-Credit insuffisant - YELOW 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76ece060-4d89-4a27-a0e8-abe90f1a9392</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0efe9ffc-4c44-4f91-8a40-e932d52d5c48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/04-Credit insuffisant - YELOW 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83be4c7d-64a3-4e82-8ed8-a888ed3eb29e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e56bc8b-1dab-43be-a0c6-214dc3c585f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/03-Credit insuffisant - YELOW FACEBOBAKA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22216591-83fe-459a-9216-3bbff8ed2b0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>559422ff-3544-45bb-a471-e9bd088954e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/02-Credit insuffisant - YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26346712-5ec5-4cbb-8c3e-f7fbc5a8db1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5154de5-b417-405b-bf45-510bb0474b56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/03-Crédit insuffisant/01-Credit insuffisant - YELOW 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78e3c606-1dd2-44dd-9eb5-9b4d4239276c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca976993-7517-4b0b-ac01-7623af2f96af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/06-Annuler achat promotion - YELOW FACEBOBAKA plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67aa6665-6dc4-4cc8-adc6-b80a40e40df9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24c5992f-6287-4e95-9a75-f0eed5543285</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/05-Annuler achat promotion - YELOW 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ac181a-8197-46fe-81d1-d391c2b85859</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db3db0e1-d634-434a-8c34-564deb487f93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/04-Annuler achat promotion - YELOW 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36bf0539-6790-45e9-8d00-bfdad008e27d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbccdc6a-d2ea-4340-baad-c491344d9bce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/03-Annuler achat promotion - YELOW FACEBOBAKA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c49ef4-1602-492c-beea-eac0f372ea77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c5dac6b-5809-4530-ad8f-904e55187c7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/02-Annuler achat promotion - YELOW SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66c52434-dc78-4c3f-9513-de82dc8891ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5d60f71-55d1-4e5c-b1e1-36717821ffc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promotion/04-YELOW/04-Annulation Promotion/01-Annuler achat promotion - YELOW 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5017e5d8-5185-4e8c-a3d0-7423903e9451</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76df4580-204e-4201-a131-5adc8e7f4bcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
