<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>First FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>296f5893-8aa8-4846-aea4-0190cb9d5e81</testSuiteGuid>
   <testCaseLink>
      <guid>893517ae-a878-4f67-ad0f-1539e6c06dfb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b48edafd-7d09-4b4b-81a1-c0892d74cefc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/01-Menu FIRST/Menu FIRST (VOIX - SMS - INTERNET)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddaaed0c-b88b-40eb-bf14-f9b8d9e8a84e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e7a80c6-b18f-42ef-a6e6-7c6de34b0025</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/01-Menu FIRST/Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>209b7932-52f4-4d21-8a1e-c44f1c25666e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>798c435a-310b-4044-8ab6-be34468388f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/02-Acheter Offre FIRST (Voix - SMS - Internet)/05-Achat FIRSTpour soi - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcf5f3ed-5d6d-41ee-8442-1ee9ac619750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80eafcea-bb38-4750-bb84-358b1a0bffb0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b89906a-bf9b-45ca-b3d4-5d6b936ea977</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/02-Acheter Offre FIRST (Voix - SMS - Internet)/04-Achat FIRSTpour soi - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3d219c3-5ec7-4d4c-a060-f142ed9fd16c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1603c55f-59ce-404e-8bac-b065e44ed9f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f95a53c-d28b-46fe-a439-ba48103b8784</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/02-Acheter Offre FIRST (Voix - SMS - Internet)/03-Achat FIRSTpour soi - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0924e688-1884-4f2e-aa18-6cf2608041db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd0e719f-cffb-4ad4-bf26-add1a622f81b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc8d22fc-cc4a-4d32-8b31-a9eae9bfc760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/02-Acheter Offre FIRST (Voix - SMS - Internet)/02-Achat FIRSTpour soi - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42097bbb-0913-433d-9eb6-c24d82e49dbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15f8ba49-0461-4c0a-aa72-e18f2a478660</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>424bbd4c-4e94-410f-a0a5-b60855a418c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/02-Acheter Offre FIRST (Voix - SMS - Internet)/01-Achat FIRSTpour soi - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b57a54-8a83-40af-a90b-c6c3b8f889a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>965e47bd-46c4-42bf-a42b-24ed6fefd188</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5ac09c8-a90c-485d-88d4-3c8e40c64235</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/03-Achat FIRST avec crédit Insuffisant/05-Credit insuffisant - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>656d8c2b-e7f3-447e-adf1-b5b01fb04936</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05f5ec6d-47e9-44fe-8963-1046a2ab0053</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/03-Achat FIRST avec crédit Insuffisant/04-Credit insuffisant - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc0670ab-eb1f-44ca-8555-b3bd5c83b362</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b3c89dc-19d8-43b3-81ad-a5400c12f1d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/03-Achat FIRST avec crédit Insuffisant/03-Credit insuffisant - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>892f0995-d1b3-41eb-a9f0-40b35c2da5bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37d3bef9-9d8d-4e36-b1b2-a35d03618529</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/03-Achat FIRST avec crédit Insuffisant/02-Credit insuffisant - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baf2d9ff-96ec-4ee2-b4c2-c6b7b308f28e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>339cd2eb-b8a6-46d8-abfa-1e6f7955caa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/03-Achat FIRST avec crédit Insuffisant/01-Credit insuffisant - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32251949-328b-40ab-b181-da658f25cc7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5aa31c47-e6eb-4702-ad92-94b784a2bf6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/04-Achat FIRST avec numéro non eligible/05-Non eligible - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0d04c37-810e-4e04-8d2f-17f52f602147</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3ba05d9-87a3-43b8-8576-e5fe03e8cadf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/04-Achat FIRST avec numéro non eligible/04-Non eligible - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89fe46eb-4ab6-4719-860d-d80ad0e8adf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02c6e60d-1b7a-410d-8502-0ddeb8e3dd55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/04-Achat FIRST avec numéro non eligible/03-Non eligible - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0e6981e-c068-4126-9864-12ec6d839e1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bf6ebf6-54aa-4adb-bfcc-9af548f351d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/04-Achat FIRST avec numéro non eligible/02-Non eligible - FIRST PREMIUM 15000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58bd2e0f-a2e9-4887-8670-145cc1dd33b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3de138fa-006f-445a-a2b8-a1c2bdcf28fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/04-Achat FIRST avec numéro non eligible/01-Non eligible - FIRST PREMIUM 10000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0492c5d0-f073-4fde-ad00-c3df1ef0202c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a14be64d-eedf-457a-a286-dfa4af5547a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/05-Consulter offre FIRST (359)/05-Info conso - CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bb31e3e-af12-45e4-8cc9-962746ecc9fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b16dfe7-70e8-4e37-8238-1f2c47c0c709</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/05-Consulter offre FIRST (359)/04-Info conso - ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ef7f9f-9630-4325-9d1d-b97c56010606</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b1e07ad-f256-4eaf-8317-6510d7a3446e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/05-Consulter offre FIRST (359)/03-Info conso - PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0beb843-2cb0-4476-b5cc-40ef52e1020c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>703ebb81-899d-4894-87c3-162f4534f60c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/05-Consulter offre FIRST (359)/02-Info conso - PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>528d9517-6139-4f39-bba6-e083fa6e60f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f393ee8-a72d-418a-9a33-a7b768d10670</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/05-Consulter offre FIRST (359)/01-Info conso - PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b815ee-b307-40fb-8559-70732d0ec4d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d9cd497-4671-4ce7-8bb3-0bf953d698aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/01-Etat de renouvellement activé - FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2682f904-b749-4e1b-bf21-d84bc999241f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9487770-56ca-43ea-b9f6-88f8d4b659f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/02-Etat de renouvellement activé - FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcb6e2bb-65b9-436c-ac6d-ef51bce06d38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74d31d05-a12e-4a90-8f33-543a64651422</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/03-Etat de renouvellement activé - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8696d139-4e26-43d8-ac98-fded0398f6c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d79992c-cdc6-4ac6-b4d6-bf8ef4dc62d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/04-Etat de renouvellement activé - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945a89a2-74b5-4ef8-849b-aa4df0e396bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bbca1ab-303e-47c8-be06-d31cb80e1586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/05-Etat de renouvellement activé - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354af3ed-1b02-40c3-8cad-81ad2943500c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>910cce58-1cc9-4164-9325-c3979a898098</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/07-Désactiver Renouvellement Offre FIRST (359)/05-Désactiver Renouvellement Offre FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d745c69b-9386-4c9a-8051-c80000d3d452</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>061fd716-0abb-467d-b93d-c58967e4ef2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/07-Désactiver Renouvellement Offre FIRST (359)/04-Désactiver Renouvellement Offre FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b5bfd80-0d82-4438-997a-d4197e2e8b5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4d1a409-815a-4ffb-b39a-f713d06ca18c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/07-Désactiver Renouvellement Offre FIRST (359)/03-Désactiver Renouvellement Offre FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d0b842-5896-4688-87c8-24c21ba59a08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4f6b5c7-b8f7-438a-b69e-9491b40cb20c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/07-Désactiver Renouvellement Offre FIRST (359)/02-Désactiver Renouvellement Offre FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1923a2-e154-4dbb-b5cf-670defab1c8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de34d0fa-88e7-4a2c-a04c-87c042c51e21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/07-Désactiver Renouvellement Offre FIRST (359)/01-Désactiver Renouvellement Offre FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf28db5d-e627-4b78-bf9c-f5f1fffa9638</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>331aa1d9-d0ec-4948-b8f1-c74281fea55c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/06-Etat de renouvellement désactivé- FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d304d133-480c-49ba-937f-195d9e2a460f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65d909fd-59dc-4979-8789-9852980f3fe5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/07-Etat de renouvellement déactivé - FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fef7cc25-a72f-4cd7-971c-57633d16251c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>496927eb-12f6-468c-9188-46355061bfc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/08-Etat de renouvellement déactivé - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a54e0d8-7092-430e-86a5-755fed2448cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68b17aae-e05d-4181-9467-da2be8eb4ab5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/09-Etat de renouvellement déactivé - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99db4d32-cab9-4af6-9a6d-3417a75af8b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06defca2-7e86-46f2-ac5a-a01620cf5288</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/10-Etat de renouvellement déactivé - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4694861-ad19-4c11-bec7-752b2c1b5ccb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e64b0e53-ad61-42b8-9e3e-3100e613480f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/09-Reactiver Renouvellement Offre FIRST (359)/05-Activer Renouvellement Offre FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16247833-04cc-4ea4-845e-2c3b998a8533</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>defc603c-aba5-42c4-8772-5c3a28256a67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/09-Reactiver Renouvellement Offre FIRST (359)/04-Activer Renouvellement Offre FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82db2246-aece-4dd8-8e7e-7f487e52d301</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae10dfc8-1675-4485-8a1f-d8e133c3e9bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/09-Reactiver Renouvellement Offre FIRST (359)/03-Activer Renouvellement Offre FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aeee900-92bb-485b-8582-90f60a10f9bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bd3ae69-9f9b-4984-b658-7ca14050d3d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/09-Reactiver Renouvellement Offre FIRST (359)/02-Activer Renouvellement Offre FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56498f1-193b-451b-a888-4194d909b24e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe33df4d-6265-4858-8342-7c7b3e655c5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/09-Reactiver Renouvellement Offre FIRST (359)/01-Activer Renouvellement Offre FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd865301-2369-49b7-b4f8-330fe3f26490</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>847e6924-2adb-4dbb-ba15-09f73d120d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/01-Etat de renouvellement activé - FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2682f904-b749-4e1b-bf21-d84bc999241f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b94efb59-cbf6-4099-ac61-1859da76f08b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/02-Etat de renouvellement activé - FIRST PREMIUM plus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcb6e2bb-65b9-436c-ac6d-ef51bce06d38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b218ea3-ee66-448f-978d-8a5dfb360103</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/03-Etat de renouvellement activé - FIRST PRESTIGE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8696d139-4e26-43d8-ac98-fded0398f6c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c670ff32-41d8-4c53-a713-b4226897cc83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/04-Etat de renouvellement activé - FIRST ROYAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945a89a2-74b5-4ef8-849b-aa4df0e396bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>070a2613-03d8-434f-9c82-465d58b69558</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/03-FIRST/08-Consulter etat de renouvellement Offre (359)/05-Etat de renouvellement activé - FIRST CLASSIQUE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354af3ed-1b02-40c3-8cad-81ad2943500c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
