<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01 - Info Credit Prepaid FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>69073233-b6cc-403a-86a4-5bebf954decf</testSuiteGuid>
   <testCaseLink>
      <guid>78bc61d0-37ab-4bc2-b3df-b84dab5591a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Info crédit prepaid/01 - Consulter le menu Info crédit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197cc6ce-4c61-4cc9-9243-187642a38028</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a5663b5-9263-4f37-9d84-9d1120be1660</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Info crédit prepaid/02 - Consulter solde credit - Client Postpaid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b62db15f-6be8-4aa5-ad76-063c7d46fa7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cce1c26-66f4-4964-8353-14cab5704645</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Info crédit prepaid/03 - Consulter solde credit - Client Prépayé</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694dd3f8-4d67-41ae-a959-066b3fb299d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6563c8d3-f126-47a2-bc7f-c52c641cc843</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Services TELMA/Info crédit prepaid/04 - Consulter info conso internet - Client postpaid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6da4929b-afd1-4b84-9e19-5eac33de6cf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deb5edc7-5c43-430a-ad39-cb8b5bcca2b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Info crédit prepaid/05 - Consulter bonus Internet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c473d3c-aa5b-4f65-80b9-b26a5ce11f58</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
