<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Envoyer Credit-Offre-Mega MG</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a030f554-c8aa-48d2-949b-3138aeebaeff</testSuiteGuid>
   <testCaseLink>
      <guid>87dc8fca-40b2-4a95-b56e-86e53fab758b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/01-Menu envoyer crédit/Consulter le menu envoyer crédit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ea42391-d44f-4101-bb21-6f65d2ca24e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec8de61d-ab52-4713-b2e8-475fb40ed5ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/02-Saisie Numero destinataire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f23da474-d01a-4dc5-9725-cfd41b646505</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97110dc7-117c-4dc3-8d06-9223001e869d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>553ade15-0e37-4898-b95e-90def988b7d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/03-Saisie Montant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baba804d-b5a6-40c8-8af8-1ba7d0f98be8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d20ecd5-e9a8-4af2-a15f-9141685287fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/04-Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c8b6c54-5418-4804-a8b0-dc33187c7b04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f4fc530-cac0-4ecb-a035-bcd75ca8bf45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cad44a21-62f8-4ea5-a99b-02e6abdeb61d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17355d15-961b-4eb1-afad-d36c237a5c87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/05-Crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d38359-bb38-44bf-b8f2-c719682d90b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098fd766-e164-48b5-b21f-80c4e19387ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>141e7b4a-d79b-484c-9a90-9b024e42b20a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cf86ca0-a1f3-41cf-a917-319f53f58af3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeafbfe8-9968-4689-871c-ff9d1e33d45f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6720ea56-8e89-496c-b810-a5683129e446</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/01-Envoyer credit avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>975c3894-bd15-4659-aed7-be3829e6cd2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7716edde-81e4-4fd8-82fd-2d60d01e068d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03ed4103-dfcc-4f5c-89e1-6486d0903595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>319ae716-b960-42db-84df-8283e1e53b77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>513dae71-94f8-4fc7-9449-c8800899e3fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd328d94-a83a-40c0-a667-07817d8debfd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/02-Envoyer crédit/06-Crédit suffisant mais frais non inclus</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa014bdd-a7f7-4643-864f-203a30fff575</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81e695b4-84a7-4e3c-9ca4-5e1535143efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>717d0e96-d378-4512-9004-2f0b84501ef2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd2d1421-49d3-4058-8abe-c4624289d17a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>135d8453-c717-4a05-bfe0-7d6263771912</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03a96546-9394-48e7-9768-f6dc95b2de26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/01-Menu offre/01-Consulter menu offre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e27747-3622-4226-9e5d-03b45b98a67b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7110749-4a40-4e9b-ac23-7a2b9b5f0741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67a733fc-a244-4349-8a97-730880bea3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>618166a7-2d82-4cae-84c3-0ba260154c82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd7b0ab6-f5fb-4222-bbd7-7f895f2d3cf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29b35bc5-7752-47ee-956d-a4fbff5ad15c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/02-Envoyer offre MORA FIRST YELOW NET/01-Envoyer offre MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3659cf7-006e-43a4-8c32-4319906a6e50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f191f74-729d-4e92-b833-ada9e2e3f930</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8b7f420-507f-4b6d-b56a-2b41c8e7290a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6f1fd70-5d74-40e3-8ea6-12894948a6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b94b7579-03ee-48aa-98ce-793d00988081</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f3cf980-2ae6-4ec9-afcc-1b0fedaa910d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/02-Envoyer offre MORA FIRST YELOW NET/02-Envoyer offre FIRST PREMIUM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae5d15e7-b46d-4015-897e-73f5067a289a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e80fd7-803d-44c4-a908-a2fc59ab97e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91d141e0-e869-46a0-9875-7b16da12cfaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deb0daa3-dfcc-43bd-827a-cdec9f859694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e831e538-532a-4d91-87a6-ae3c7c9e65f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b89830aa-119b-4154-a2a5-5266ce2c01b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/02-Envoyer offre MORA FIRST YELOW NET/03-Envoyer offre YELOW100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974b9104-263d-47bb-aa7f-ec69201395cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63e494f1-424f-401d-8b5f-6958f3c79428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3c17b7d-8cfb-40ed-8dbb-d2f03463c793</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>916b1d9e-40d2-4e1d-bd8c-fb72ce433141</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c769bf8a-25df-4ac7-9b91-c8e7bd3c4f13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53db6e4f-b920-4ace-a785-b14a98a8fc92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/02-Envoyer offre MORA FIRST YELOW NET/04-Envoyer offre TELMA NET ONE DAY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d0644e0-dab2-447e-bdea-ad06e03483d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0d06317-92cf-4e35-a8e5-4fe89f3ac369</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eeee053-f20c-43ae-a46a-fabc9d93ddd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7851b558-ba64-4d23-b192-ce3d12d05902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44e67d6b-8e0a-428c-a902-5126a05c6eba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>412f8138-a6f8-4046-8c3f-966b15eab535</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/01-Saisie Numero destinataire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>448ed6f8-eaaa-4470-8fd0-6588a4d0bd4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce844db-767e-42ae-adf0-4a334a10561a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a776fa47-8c89-4ffa-924b-1a79afa9329e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/02-Choisir un menu offre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0a9e2d2-7e5f-481b-9649-eb7dde339187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bbdbd1f-6ac0-46c3-8d51-1b621a51d06f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58a7d11b-905d-4f3c-8e66-7ef511d2d37d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/03-Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0f36a45-34f6-4336-b87f-1aa389be338b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8504bf69-6b83-47ac-9c82-e23a0bbbf512</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e37c0c6-d401-4d67-82a5-225776c5b5f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/04-Crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1fb40b1-1127-4d52-9e83-2ce9aba583e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3982a2b5-9069-490f-a85b-b1a1ef3d6f0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1763726d-3a92-4e8f-a841-1382934f5634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05173d2c-ef2d-435e-9921-a04c55c18451</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7411e987-95cc-4da6-a737-39c89a878b8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1717c272-4293-4643-aaa4-e7b490482a22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/05-Envoyer offre MORA a un numero postpaid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22435465-ba0d-4e2d-8c13-46e373733514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abab8bba-094b-42e9-b117-fcf9bbe45e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4792acb0-e43d-4f3b-a042-f40393b4e6fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dec17d0f-0368-478c-a5a7-bb04b80b4fb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow Facebobaka plus pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57510e91-f119-4433-a58c-a01e4e8b8128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ade298-8100-4f1c-9975-9e3b523ad9f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b905d16b-9d1a-4a71-9bdc-59d85c8ef3d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/04-YELOW/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow facebobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75cf214f-f353-4107-be25-a10d57cd63ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d2b5310-1f8a-4041-86e5-d619e9280116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/03-Envoyer offre/Envoi offre non abouti/06-Envoyer offre a quelqun qui a atteint son limite offre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45872633-4e27-4443-9641-5e5a510c0e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8c74b3f-00f1-45f1-8ce1-afa7c961afb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32ad438-c7e7-41a7-ad19-56042a7eb64e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e609094f-a0f7-4a37-a540-934e0f4b40f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/06-Partage mega - pas d offre</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d4c6d7e-3bcc-4a2d-832d-b2125732f085</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcd93a7-75df-4021-a2df-65b4f411f7ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32174c28-4f97-4890-8ece-a7bb4441a98c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/05-TELMA NET/02-Achat offre TELMA NET/03-TELMA NET Mensuel/01-Achat offre pour soi - TELMA net ONE MONTH 1,5 Go</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7167b24f-25f1-4cfd-a784-4bad3e7896a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e6ef065-c013-4bb3-929a-b58a4f455f03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4dc72b8-2d1b-415b-b3b3-e0520bcae62e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/01-Partager mega avec succès</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a4353d9-db68-4199-8e4e-6175c03f58fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be1aa40f-61c5-4e26-b71a-5ef27469db43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c070044b-de4c-460e-a255-8af2c5fc26ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de382949-b290-4545-ba54-b74d49ef72c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1a8ac2b-584d-44eb-933e-48dcef70f33c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/02-Partager mega - numéro déjà enregistré</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1394ae88-8b4a-4564-b29a-84c047461250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca86309b-9833-4123-aac6-df7a7fd5414a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0846da4d-79cc-438a-8c00-041683e7a62b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da87ac13-69a7-4c48-b033-e43227a10ac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbbee797-8ffd-4656-bc3d-ed51732033b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ed94369-2345-4c1e-868d-45784268d9b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/03-Saisie Numero destinataire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665068f8-87e2-4516-8241-cf7f2b894113</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a948c2-a459-45eb-9cd1-1ac37b079082</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dc04f6f-c8c3-4a1d-9934-eda1d6f5ec27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/04-Choisir un menu Mega inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6027dba8-cf47-4447-8a9f-692e43b619a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72970062-4578-4a82-9f9d-626585ae8895</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c2abac9-7ae2-4b64-9f2f-97b0830a7ec9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/05-Saisie PIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>745735ee-20a1-44e6-ae03-c2761b7b8f31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd60fecc-8ba4-4c27-9849-23765c9c18b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fefce1-816e-4570-b4a2-cfa34623adca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dd34cbb-28ff-4b43-a610-fb5af699ed3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Envoyer crédit, offre, mega/04-Partage Mega/07-Partage mega - non certifié MVola</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96a83475-cd18-455b-9642-1007ae3e2b3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ea2e43-ed5b-4382-a76e-4df1a90e1425</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>217d1a05-1a24-4f4b-bcb8-de8ff0836c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00-Called Test Case/Changer de langue</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3c6a709-03d4-49f5-85a3-4205a8dc8a53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
