<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Yelow FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b23d8f54-1acc-4f6a-aa67-d560625f7acc</testSuiteGuid>
   <testCaseLink>
      <guid>fd0938a2-532d-4999-99d3-3c35506b575c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1cf260f1-5d66-4d83-b5a7-06c53136b8fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/01-Menu Yelow (SMS - INTERNET)/Consulter le menu YELOW (SMS - INTERNET)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d57d62-bc94-440a-972f-88da417bd059</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f1ac12f-dcf7-4940-b79d-cbedef4c3c32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Non elligible à l achat offre Yelow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad59dd24-03ab-43ce-bc2c-e9b71ff2e107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80531d74-fb56-488d-aa85-c152e7678e1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1431edb9-c304-4352-be23-38ee31531de0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow avec crédit insuffisant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d79176ea-7947-4187-92a2-69b2b08bf9f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4c24283-c1c5-4c6e-ba2e-e238d7154808</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13be4512-44ac-4959-b7b5-d1f7abea778c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW100 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80114e65-62df-41b8-b32b-619041f39c74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c63b0d-8c42-4e95-a08a-9e2304fbe06c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bd1ae78-a3d3-4644-b2e4-06c0d6d4a6d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW SMS pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34e047d8-c070-4570-9242-1ebb36aba141</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8f3c704-8a16-4db9-a082-34d2b37eca7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb0bb020-a659-41bc-8686-a92567f71dd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat Yelow Facebobaka pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a490d745-3218-4f5f-b6b0-a636e3b3dda2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b49c9d01-17d0-4d3b-92ca-43727f6df345</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d89e421a-25e6-4798-b689-ddd1505315c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW 1000 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aedc1a3-4f5e-4b40-9aca-54914786331e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff8f3acd-9710-423f-b390-44aa16dc4b5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec5a4a0c-bfa3-494a-b051-e630e8c33c8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/02-Acheter offre Yelow (SMS - INTERNET)/Achat offre YELOW100 pour soi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80114e65-62df-41b8-b32b-619041f39c74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c63b0d-8c42-4e95-a08a-9e2304fbe06c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3028c61d-0afa-428f-9321-14cbb5e99c5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f013d39f-0381-4501-9646-42cc08ac6621</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eff69b9a-0bc5-49b8-a9a1-c80115561454</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6eadc95-53da-413c-b538-23a0dda02ec9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40ece721-d2c5-498e-899f-d2d0b75da62d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow facebobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75cf214f-f353-4107-be25-a10d57cd63ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>098d66a2-6d34-4d63-8229-edbe6cf92737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/03-Achat limité offre Yelow (SMS - INTERNET)/Limite journalière d achat - Yelow 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f8b0306-e762-4afc-888b-500b8918917a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b5c5c85-885a-406b-8320-a9d12e2ba08f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/04-Consulter offre Yelow (SMS- INTERNET)/Consulter offre Yelow 100</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c19a8b1-ad3b-43f6-ba6c-1042f63c18c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1243b2e-9f31-4182-a74a-77e534094313</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/04-Consulter offre Yelow (SMS- INTERNET)/Consulter offre Yelow SMS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7896fb2a-03af-43d5-a11d-647e4d9b9bf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f50fdddb-5285-4918-bf54-9db07de491ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/04-Consulter offre Yelow (SMS- INTERNET)/Consulter offre Yelow 1000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec16ca12-b3c3-4b85-a57e-79539bbed433</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfd195ea-658d-43ae-90dd-8742c079ea3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/04-Consulter offre Yelow (SMS- INTERNET)/Consulter offre Yelow Facebobaka</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>748cc56d-d5a2-4699-87f6-e4f6ec1afbe1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03fa8126-6bb5-492a-8b9c-0b8a8a550c88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/YELOW (SMS - INTERNET)/04-Consulter offre Yelow (SMS- INTERNET)/Consulter offre Yelow 200</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afbb32be-db72-4440-a111-cce14d55ff69</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
