<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Mora FR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>350c0959-4166-4484-a182-57dc4b462f7f</testSuiteGuid>
   <testCaseLink>
      <guid>6db6e479-b8dc-4dcb-ad56-90888cc402c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/01-Menu Changer de Tarif (commun)/Consulter le menu Changer de tarif</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d931057-5adf-4c91-bd82-5857ed324623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20c0b557-ba7a-4d3a-a78a-e08293d0b724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/01-Menu MORA (Voix - SMS -Internet)/Consulter Menu Mora</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5269138-352d-4422-90e5-f1a43999da01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fee4469-4042-4437-9406-ea910216e5db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/01-Menu MORA (Voix - SMS -Internet)/Choisir un menu offrre inexistant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c7b4c3e-5f54-49ef-85e7-05d4c917d2d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbda095f-a885-41c5-8ae2-224ee7bd7782</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/07-Achat MORA pour soi - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e6f430-fc34-4ed1-92bf-cd9c85747b57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8e40f03-2ff0-4580-946b-e4e00611a513</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dd5bc56-7c42-4a3a-9e3d-0f9cac7d2953</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/06-Achat MORA pour soi - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad270b9c-5d72-40c1-8299-b62c59835853</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea405ea-ff3c-46c0-aff2-0e0b6a6612d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ac5aff7-160e-4f7c-91d4-2846076db513</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/05-Achat MORA pour soi - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87a7da40-aed6-431c-9c8a-8d1240eb6a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6908c7d-7c23-4fa9-ba54-d3696bf338e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15bfe08d-eec5-479a-b4ea-4ebf03655331</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/04-Achat MORA pour soi - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3853abd8-e9e7-4a5d-bfe2-a886ab4f6528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d695b3a-7184-473c-8755-1b431f8b9131</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99e39ac5-6e39-4732-b86b-29f97e249263</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/03-Achat MORA pour soi - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abeb6f9d-99b0-44a9-bc51-751eda9dd6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fbe4689-29a7-4107-a860-82c1bb4c0402</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e2c48bc-ee50-42a3-a6de-53704262e822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/02-Achat MORA pour soi - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4c2a532-4dcf-4f49-a69d-46d86b8d5865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0381f1f7-617b-48c5-87cf-d6e98acbaedc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76cf192f-e38e-4c82-b906-e2b19cfe0ca9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/02-Acheter offre MORA/01-Achat MORA pour soi - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20783233-a543-4a0b-bbca-6794872d19fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4517c976-5b79-4a4d-9225-4e09f58e43a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eeb0022-f72a-4ff3-a473-a998197573ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/07-Crédit insuffisant - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf47aa83-a9ce-41db-b72d-42f96d7c2abd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2cdf110-e2bb-45d2-aad2-c300168a6187</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/06-Crédit insuffisant - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e817b1a-c8b4-48d5-96dd-cd6c35646a76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6fe90b7-c788-4aa6-b970-e54558c3b136</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/05-Crédit insuffisant - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed886279-8f58-4eb6-b6c6-246bb6f29985</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10f58aa6-27e7-446e-bd6e-a6b101b168d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/04-Crédit insuffisant - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>648dd567-26e2-424b-825d-bcf48a06740f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6beff3b8-0685-4510-a825-ffd64c0c0527</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/03-Crédit insuffisant - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3592b4d3-50c3-4a54-8cd2-31d8f410a225</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b921f6d2-6aec-4ba9-9a10-3c26b3aed971</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/02-Crédit insuffisant - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad57b361-d8ca-454d-9197-ac2c06dc1ced</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0416d1dc-2a9d-4d83-a143-535e38141485</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/03-Achat MORA avec crédit Insuffisant/01-Crédit insuffisant - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbf74fa-8784-4d81-b5f7-2ec3c3740dd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66fd4213-ac81-4b8e-9494-4fdecf3c97da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/07-Non eligible - MORA INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7b29cb-5b27-4d18-bbab-4437fffaf16e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22642837-aa77-4923-9581-ed130611f487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/06-Non eligible - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7149c89d-ad7a-4b19-9d5d-ed2aa4aa09c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac2a3e52-b497-4802-ad68-f4e0d6012e1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/05-Non eligible - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>301c8825-d306-4c63-bce9-00714c67ae7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98e219ef-bfc6-4e8c-8654-cbd04a38b026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/04-Non eligible - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3337d1d7-a037-4edf-ad37-76a40ba84b2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb5e9e46-9345-4101-be4a-5c90408ad3e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/03-Non eligible - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7943894b-8f2b-4700-9d3a-ea7e76f8d76d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f504b5bf-e51f-49ea-8641-f8434bfc4cfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/02-Non eligible - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da5f4c4d-b671-4ae6-8645-559acff9fe45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53c892fc-489d-420a-ad19-623b1a414e8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/04-Achat MORA avec numéro non eligible/01-Non eligible - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96fafc71-8ebc-46ef-9779-7da6823dc1fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf1e7375-84de-4bf7-a285-c5883e4a931c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/07-Info conso - Mora INTERNATIONAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cec94e3-0235-4ee4-a512-5e77a479181d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ea62cf7-fbba-4aef-b0be-07036895254b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/06-Info conso - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d629d7c-d8b4-4b27-987c-249e3e3f4978</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>420fb403-b081-4f15-8650-1b6584fe2dfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/05-Info conso - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>066ed3e1-4e2e-4779-b7d1-73a5b1a73ef1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0ef6eaf-974e-44d2-a369-c57dd16cda46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/04-Info conso - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d453d16-f173-4d26-a919-4c86086754e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>849c5ead-397c-4a8d-85cf-531be081cddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/03-Info conso - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5463af58-68d2-4090-a6b3-6b301f753537</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6d32f80-c870-41cd-9d3e-76857d3ac0bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/02-Info conso - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71dec97-88de-41e3-9b4a-1083952bca42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e378baf-5e32-4675-9a79-0bbdba364212</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/05-Consulter offre MORA (359)/01-Info conso - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fdbf12-1463-4c70-8511-0bfa8c1a05f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c18d92ff-8b64-4faa-abd0-0a795b071b61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/06-Limite d achat MORA/02-Nombre atteint journalier - MORA TEAM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6b7eca-d668-4754-ab26-4d25d4bac025</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc3e759a-8b76-47fb-b6e1-4dcc3b0ac4b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/06-Limite d achat MORA/01-Nombre atteint journalier - MORA NIGHT</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec322cf2-9060-422a-b6fb-8478084f71e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deb08de3-e1fb-4f09-9435-c2b9597b41cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/01-Etat de renouvellement activé - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288d6496-14b3-4886-9751-3e623556da26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0d5caa6-5355-4db1-8e8e-33f17e0f98eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/02-Etat de renouvellement activé - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09e5535d-f0ce-423e-ba91-7912501cc9c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7940a8ca-ce1b-4cc3-a878-5ee95cca2f5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/03-Etat de renouvellement activé - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2967453-a49b-4c5c-82b6-862976010cf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dc07340-22ef-485e-84fd-ed6f343bbc88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/04-Etat de renouvellement activé - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97852932-ab51-4439-b554-e8fc95a344a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76d98657-d145-4577-9ddd-d3f9a6c45f9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/07-Désactiver Renouvellement Offre MORA (359)/04-Désactiver Renouvellement Offre MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4edb1d4a-b0fa-4fdb-a3e7-7e1d6bc2edbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cef89c9c-fd87-4e0b-b62a-2091c022e155</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/07-Désactiver Renouvellement Offre MORA (359)/03-Désactiver Renouvellement Offre MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7ab6291-f1cb-4b21-b4df-059ad8bba249</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>566ac3b9-2a4f-4cee-a6e2-ea83dfbff1ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/07-Désactiver Renouvellement Offre MORA (359)/02-Désactiver Renouvellement Offre MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d708927d-a608-4746-9a0b-62922be5a706</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fa3ba07-c441-41a5-8304-a24e2d2f17a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/07-Désactiver Renouvellement Offre MORA (359)/01-Désactiver Renouvellement Offre MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86af4901-83f8-4d11-9f92-7a4cda433ab9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f5768b0-d07f-44d9-878e-9707be1c5025</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/05-Etat de renouvellement desactivé- MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a25b5e26-9f9d-49d9-8666-53f67223c291</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5afd1748-23de-4ef5-90a3-ad8043a1cfbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/06-Etat de renouvellement desactivé - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4cf698-2d28-4fd3-b287-38dfe157e2b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f70100a6-3b04-4f99-8ccf-89d6b6d88c65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/07-Etat de renouvellement desactivé - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf09d508-f712-4ae7-b626-8cbd1691baa4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>432fdfa0-ad9b-44b0-9ebf-63a3bd591b49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/08-Etat de renouvellement desactivé - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b232dd95-8a62-40cf-b4da-3e5a2f5ad4b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>057dcdd1-dc31-421d-b74b-8e10ceb33b19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/09-Reactiver Renouvellement Offre MORA (359)/01-Activer Renouvellement Offre MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3bc366d-f091-49e1-ba62-8ffbb9fe603d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdeb1d2b-1c04-4cc4-990a-2d547dab0d16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/09-Reactiver Renouvellement Offre MORA (359)/02-Activer Renouvellement Offre MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5031553-6622-4175-a770-645ca536019b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3660b63c-f104-4e45-a851-1c9409f871e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/09-Reactiver Renouvellement Offre MORA (359)/03-Activer Renouvellement Offre MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbf48376-8451-4c10-9104-a2d3eedc7db9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d135f38-5ffa-4417-b20d-dc9d2d21a773</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/09-Reactiver Renouvellement Offre MORA (359)/04-Activer Renouvellement Offre MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cf57540-dd99-4aab-b929-2e4abcb166bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19e3b774-9f6d-4831-b3a3-ec5508568eb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/01-Etat de renouvellement activé - MORA 500</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288d6496-14b3-4886-9751-3e623556da26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>841ce949-d254-4f81-ad62-816785eda8a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/02-Etat de renouvellement activé - MORA ONE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09e5535d-f0ce-423e-ba91-7912501cc9c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c287438-4a51-4a6a-8aa9-ea9277203d46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/03-Etat de renouvellement activé - MORA 2000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2967453-a49b-4c5c-82b6-862976010cf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fcd3b5f-bbf1-4684-85eb-5427537bc7a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Services TELMA/Changer de tarif/02-MORA/08-Consulter etat de renouvellement Offre (359)/04-Etat de renouvellement activé - MORA 5000</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97852932-ab51-4439-b554-e8fc95a344a1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
