<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Mon identité (MG)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>172738b3-3b5c-4f8d-9eed-b6e12b01a542</testSuiteGuid>
   <testCaseLink>
      <guid>aaf8daf4-e6ac-4cf6-9afe-ce0fa143bdfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/01-Menu mon identite/Consulter le menu Mon identité</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5356a7b7-f235-496a-9e5d-c48e66fdb312</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c39a138-7e12-44c6-9cbe-06b69e9b617e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - Saisie Nom</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce49490d-909d-4c05-85d7-96f8f982ab36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cadb140b-68d7-44c1-a6a5-428667e69d99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - Saisie Prénom</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d07e9e-c283-42e0-a601-26a1cd03b795</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1c9b9ac-c53a-4ec7-b08a-7b0b4a001946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a455ee98-25ca-4ec5-840a-63da1aa7291b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - Saisie Pièce d identité</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d43bea9c-e520-4fe3-a228-80b8ee34c4eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb3b4b7f-7b77-493f-bc77-f4aa7c28b061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63795e41-eb80-419c-8420-d6a3a639b0e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e0c15c5-0eea-41a5-a52e-d4df64137078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/03-Consulter mon identité/Consulter identité - client non inscrit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8755e3d-9522-4a0c-98c1-83d7bca89119</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c3e3a50-8c2f-4b37-91a6-6da73efb9e7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - client non inscrit sans prénom</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dd55a06-c801-4d11-981c-5b37229950cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4248065d-ba06-4f50-aa50-759a321bc2e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8865c40-1b6f-41f5-a0fe-28d0c44c856d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44f276fd-f511-45cc-8788-bb49d45ab107</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - client non inscrit avec prénom</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9471e970-6a1f-499b-a5c3-45a552402997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>652fbe20-1a16-48cb-b9ec-7a99843823bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5cb0c81-fd03-44d9-9ba5-e6010ba7bc92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddea4f37-76f8-4e29-87ed-5a7325a5e4f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8924ab3c-c8b3-4891-a77d-eadc40538f71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/02-Renseigner mon identité/Renseigner identité - client inscrit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ac6b71b-bfee-4664-9303-b0e3c747ea25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ab9d1ef-1101-4c4e-b4ce-24c7c4022882</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mon identité/03-Consulter mon identité/Consulter identité - client inscrit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45c9ae52-c7f9-4b08-b5a3-0967e7ddea8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38353693-4d88-4b37-ae89-cc7b524ca1c8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
